name: 💡 Question about ESPD EDM
description: Question about ESPD EDM
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question request! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: user-question
    attributes:
      label: Your question
      description: Full details of the question
      placeholder: "Please provide as much details as you can about your request."  
      value: |
        # Your question 
        
        ## Full description of question request, 
        
        ## Full description of the current behaviour (optional)

        ## Full description of the expected behaviour (optional)

        ## Link to existing ESPD service, if applicable

        ## Reference to the ANNEX 2 of Regulation (EU) 2016/7, if applicable
        
        ## You may add print screens to exemplify your request

        ## Other information
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ESPD Version
      description: Which version of ESPD EDM is this question refering to?
      options:    
        - 4.0.0 (latest)
        - 3.3.0
        - 3.2.0
        - 3.1.0
        - 3.0.1
        - 3.0.0
        - 2.1.1
        - 2.1.0
        - 2.0.2
        - 2.0.1
        - 2.0.0
        - 1.0.2
        - 1.0.1
        - other
      default: 0
    validations:
      required: true
