name: ✨ Idea for a New Feature
description: Request a new feature for ESPD EDM
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature request! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: user-requirements
    attributes:
      label: Please provide the details of the idea for a new feature
      description: Full description of the new feature and the desired behaviour
      placeholder: "Please provide the following information: full description of new requirement, the expected behaviour, the reference to the ANNEX 2 of Regulation (EU) 2016/7"  
      value: |
        # Idea for a new feature

        ## Full description of the idea for new feature

        ## The expected behaviour

        ## The reference to the ANNEX 2 of Regulation (EU) 2016/7, if applicable

        ## You may add print screens to showcase your request

        ## Other information
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ESPD Version
      description: Which version of ESPD EDM is this feature to be implemented?
      options:
        - 4.0.0 (latest)
        - next
        - future
      default: 0
    validations:
      required: true
