name: 🔮 Other Request
description: Other information request about ESPD EDM
title: "[Other]: "
labels: ["help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this other information request! The ESPD Team will be back to you with an answer!
  - type: textarea
    id: other-question
    attributes:
      label: Add the the description of other information request
      description: Full description of the other information request
      placeholder: "Please provide provide the information about your request"  
      value: |
        # Other information request
    validations:
      required: true
