
=== VI.5 Financial ratios

==== Related information requirements

See formal requirements related to 'Turnover' criteria for the Extended ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-013[_tbr070-013_]

==== Differences between Basic and Extended

. The *Basic* ESPD expects the economic operator to introduce a numeric value for the ratio (e.g. 0.7, 1.2, etc.) and a description explaining the meaning (the type of ratio) of this numeric value;

. In the *Basic* ESPD the possibility of adding more than one ratio is given to the economic operator;

 . In the *Extended* ESPD the possibility of adding more than one ratio is given to the contracting authority;

. The *Extended* ESPD instead allows the contracting authority:

** To specify the number of the past recent years for which it will require Ratios;
** To specify one of the codes defined by BACH to specify the type of the ratio (see https://www.bach.banque-france.fr/[BACH Banque France], and link:https://github.com/ESPD/ESPD-EDM/tree/2.1.1/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.1.1.ods[FinancialRatioType]);
** May specify a minimum requirement (the economic operator must provide a ratio above this minimum requirement).

. The *Extended* ESPD expects the economic operator to introduce only the value of the ratio, which must be equal or greater than the minimum requirement specified by the contracting authority (if any was specified). 

. The data structures of *Basic* and *Extended* are different. See the sub-sections below about the Basic financial ratio and the Extended financial ratio for details. There is only one criterion under the category "financial ratio" and it is classified with the code:

	** CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.FINANCIAL_RATIO

. The *Extended* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis regarding this criterion.



