
=== VI.6 Risk indemnity insurance

==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].

Other requirements:
[cols="<1, <4"]
|===
|*REQUIREMENT*| Compulsory use of the code list link:https://github.com/ESPD/ESPD-EDM/tree/2.1.1/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.1.1.ods[`InsuranceType`] for the Extended ESPD of the ESPD.
|=== 

==== Differences between Basic and Extended

. In the *Basic* ESPD it is the economic operator who provides data about one risk indemnity insurance;

. In the *Extended* ESPD the contracting authority can require one minimum amount for multiple insurances, each one of a different type (see the code list link:https://github.com/ESPD/ESPD-EDM/tree/2.1.1/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.1.1.ods[`InsuranceType`]);

. In the *Extended* ESPD when the amount specified by the economic operator (EO) is lower than the minimum required, the EO will be able to indicate that the EO commits to obtain the minimum amount required (though it doesn't have it now).

. In the *Extended* ESPD, for the type of insurance "Employers (Compulsory) Liability Insurance" (and only for this type), the EO will also be able to indicate whether it is exempt or not.

. The *Extended* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis.

. For both models, *Basic* and *Extended* The only criterion defined under this data structure is classified with the code:

	** CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE

