ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Objectives and target audience

[.text-left]
The European Commission (COM) has defined a Data Model and XML vocabularies to express the ESPD documents that the ESPD Service exports and imports. However, these Data Models and XML Vocabularies are also intended to be used by any other systems that will use and/or exchange ESPD documents with other systems or in need to render its content into other formats or process them otherwise. 
This document explains and illustrates how to implement XML documents based on the Data Model and XSD Schema. We name this model "ESPD Exchange Data Model" (ESPD-EDM). The model is quite flexible and should cater for future different situations.That the model is flexible is to be considered good news, as it may be easily used for unforeseen needs. However the development of software applications and the interoperability 
between systems require concrete explicit directives and rules that guide the actual implementation of the ESPD XML documents as well as the interpretation of their content. This was the case for the implementation of the ESPD Request and ESPD Response XML documents that are currently used by the ESPD Service. 

[.text-left]
To sum up, this document is intended to *facilitate the understanding of the model underlying the implementation of ESPD Response XML documents*. With that objective in mind the reader is provided with examples and rules relating to how the content of an ESPD Response XML document SHOULD look like and be interpreted.

The content of this document is mainly addressed to the development teams from the Member States, Economic Operators, Information Providers or any other party interested in understanding how the ESPD Exchange Data Model works and how to use it to produce XML instances of the ESPD Request document.

