ifndef::imagesdir[:imagesdir: images]

[.text-left]
==== UBLExtensions element 

The UBL 2 Naming and Design Rules (NDR) establish that the first element of a 
UBL-conformant XML document should be `ext:UBLExtensions` element. If used the 
UBLExtensions MUST instantiate one or more `UBLExtension` sub-elements.

The current version of the ESPDResponse documents does not UBLExtensions, but you could use it 
for your own internal purposes. If specified in an XML document the ESPD Service would skip it.

According to the http://docs.oasis-open.org/ubl/guidelines/UBL2-Customization1.0cs01.pdf[UBL 2 Guidelines for Customization] 
the UBLExtension element found at the beginning of all UBL documents allows communities of
interest to specify additional information entities as part of a UBL standard document. The
UBLExtension element is not one of UBL's information entities. It is a structural device that
allows arbitrary extensions to a UBL document type without affecting UBL conformance. 

There are two situations where UBLExtension may be considered appropriate:

. Where the requirement is to incorporate alien content in a standard UBL document type
that cannot be contained as an Attachment.

. Where a customizing organization wishes to extend information entities in a standard UBL
document type and still have their documents be validated by the standard UBL schema. 

