[.text-left]
The fragment of XML below shows the implementation of the 
''General yearly turnover'' criterion (file Example1-ESPDResponse-total fake-Wayne Enterprises.xml):

[source,xml]
.XML example of a ''General yearly turnover'' (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.GENERAL_YEARLY) criterion 
----
  <ccv:Criterion>
      <cbc:ID schemeID="CriteriaID" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">499efc97-2ac1-4af2-9e84-323c2ca67747</cbc:ID>
      <cbc:TypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="1.0">SELECTION.ECONOMIC_FINANCIAL_STANDING</cbc:TypeCode>
      <cbc:Name>General yearly turnover</cbc:Name>
      <cbc:Description>Its general yearly turnover for the number of financial years required in the relevant notice, the procurement documents or the ESPD is as follows:</cbc:Description>
      <ccv:LegislationReference>
         <ccv-cbc:Title>DIRECTIVE 2014/24/EU OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 26 February 2014 on public procurement and repealing Directive 2004/18/EC</ccv-cbc:Title>
         <cbc:Description>On public procurement and repealing Directive 2004/18/EC</cbc:Description>
         <ccv-cbc:JurisdictionLevelCode listID="CriterionJurisdictionLevelCode" listAgencyID="EU-COM-GROW" listVersionID="1.0">EU_DIRECTIVE</ccv-cbc:JurisdictionLevelCode>
         <ccv-cbc:Article>58(3)</ccv-cbc:Article>
         <cbc:URI>http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32014L0024</cbc:URI>
      </ccv:LegislationReference>
      <ccv:RequirementGroup>
         <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">e1886054-ada4-473c-9afc-2fde82c24cf4</cbc:ID>
         <ccv:Requirement responseDataType="INDICATOR">
            <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">15335c12-ad77-4728-b5ad-3c06a60d65a4</cbc:ID>
            <cbc:Description>Your answer?</cbc:Description>
            <ccv:Response>
               <ccv-cbc:Indicator>true</ccv-cbc:Indicator><!--1-->
            </ccv:Response>
         </ccv:Requirement>
         <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">1689194b-6ecf-4ab4-ab38-7656610c25bb</cbc:ID>
            <ccv:Requirement responseDataType="QUANTITY_YEAR">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">5aacceb3-280e-42f1-b2da-3d8ac7877fe9</cbc:ID>
               <cbc:Description>Year</cbc:Description>
               <ccv:Response>
                  <cbc:Quantity unitCode="YEAR">2015</cbc:Quantity><!--2-->
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="AMOUNT">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">42db0eaa-d2dd-48cb-83ac-38d73cab9b50</cbc:ID>
               <cbc:Description>Amount</cbc:Description>
               <ccv:Response>
                  <cbc:Amount currencyID="EUR">800000000</cbc:Amount><!--3-->
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
         <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">c628dd27-8016-4d80-8660-7461f2e3ee0f</cbc:ID>
            <ccv:Requirement responseDataType="QUANTITY_YEAR">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">49a57870-7fb8-451f-a7af-fa0e7f8b97e7</cbc:ID>
               <cbc:Description>Year</cbc:Description>
               <ccv:Response>
                  <cbc:Quantity unitCode="YEAR">2014</cbc:Quantity><!--4-->
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="AMOUNT">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">4acd0a02-c267-4d05-b456-c0565c2ffd46</cbc:ID>
               <cbc:Description>Amount</cbc:Description>
               <ccv:Response>
                  <cbc:Amount currencyID="EUR">750000000</cbc:Amount><!--5-->
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
         <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">9dd09f9f-3326-4865-9d5a-f0836076fb19</cbc:ID>
            <ccv:Requirement responseDataType="QUANTITY_YEAR">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">9d0cf1cb-27bc-4747-8579-47dce4d8d490</cbc:ID>
               <cbc:Description>Year</cbc:Description>
               <ccv:Response>
                  <cbc:Quantity unitCode="YEAR">2013</cbc:Quantity><!--6-->
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="AMOUNT">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">28fb4b41-5178-4b79-ba24-d9a62fa4a658</cbc:ID>
               <cbc:Description>Amount</cbc:Description>
               <ccv:Response>
                  <cbc:Amount currencyID="EUR">650000000</cbc:Amount><!--7-->
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
         <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">962011c9-9e2e-4e7b-818e-30e8506e874f</cbc:ID>
            <ccv:Requirement responseDataType="QUANTITY_YEAR">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">17a7353d-a7a4-43ee-9cc8-b9db83eeafb3</cbc:ID>
               <cbc:Description>Year</cbc:Description>
               <ccv:Response>
                  <cbc:Quantity unitCode="YEAR">2012</cbc:Quantity><!--8-->
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="AMOUNT">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">9f278e42-aa1d-4b2e-97cd-832248aa5393</cbc:ID>
               <cbc:Description>Amount</cbc:Description>
               <ccv:Response>
                  <cbc:Amount currencyID="EUR">620000000</cbc:Amount>
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
         <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">343795e2-98e9-4cc9-8ef2-8817cec8f49a</cbc:ID>
            <ccv:Requirement responseDataType="QUANTITY_YEAR">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">34825634-5151-4e31-af1b-7eafadcf15be</cbc:ID>
               <cbc:Description>Year</cbc:Description>
               <ccv:Response>
                  <cbc:Quantity unitCode="YEAR">2011</cbc:Quantity>
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="AMOUNT">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">cc1a0b1e-dbfd-4313-a4fb-2e543b05549b</cbc:ID>
               <cbc:Description>Amount</cbc:Description>
               <ccv:Response>
                  <cbc:Amount currencyID="EUR">590000000</cbc:Amount>
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
      </ccv:RequirementGroup>
      <ccv:RequirementGroup>
         <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">9026e403-3eb6-4705-a9e9-e21a1efc867d</cbc:ID>
         <ccv:Requirement responseDataType="INDICATOR">
            <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">9dae5670-cb75-4c97-901b-96ddac5a633a</cbc:ID>
            <cbc:Description>Is this information available electronically?</cbc:Description>
            <ccv:Response>
               <ccv-cbc:Indicator>false</ccv-cbc:Indicator>
            </ccv:Response>
         </ccv:Requirement>
         <ccv:Requirement responseDataType="EVIDENCE_URL">
            <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">03bb1954-13ae-47d8-8ef8-b7fe0f22d700</cbc:ID>
            <cbc:Description>URL</cbc:Description>
            <ccv:Response/>
         </ccv:Requirement>
         <ccv:Requirement responseDataType="CODE">
            <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">e2d863a0-60cb-4e58-8c14-4c1595af48b7</cbc:ID>
            <cbc:Description>Code</cbc:Description>
            <ccv:Response/>
         </ccv:Requirement>
      </ccv:RequirementGroup>
   </ccv:Criterion>
----
<1> Data is going to be provided by the EO, hence the ''true'' indicator 
<2> Year 2012
<3> Amount corresponding to year 2012
<4> Year 2013
<5> Amount corresponding to year 2013
<6> Year 2014
<7> Amount corresponding to year 2014
<8> etc.

*NOTICE* that:

	* The XML structure and elements reproduce quite faithfully the text of the Annex to the Implementing Regulation 2016/7
	relating to the turnovers; 
	* The general rule number 3 is respected (use of the sentence ''Your answer'' to respond the Criterion);
	* In case the answer is ''yes'' three subgroups of requirements requesting year and amount 
	will have to be completed by the Economic Operator;
	* The type of data expected in the ESPDResponse.xml file are ''YEAR'' and  ''AMOUNT''. 
	Beware of the following:
		** In the case of ''YEAR'' the expected type of data is ''QUANTITY_YEAR''. The element used in the response MUST be ''cbc:QuantityType''. This element, taken from 
		the OASIS UBL-2.1 specification provide an attribute named ''unitCode''. In the ESPD Response, the responses of type QUANTITY_YEAR MUST specify the value ''YEAR'' 
		for the attribute ''cbc:unitCode'' of cbc:QuantityType;
		** In the case of the data type ''AMOUNT'', the element used in the response MUST be ''cbc:AmountType''. This element, defined in the OASIS  UBL-2.1 specification, 
		provides an attribute named ''currencyID''. In the ESPD Response, all the responses with amounts MUST always specify the currency in the
		cbc:AmountType attribute;
	* The XML maps the structures illustrated in the figures above related to the selection turnover category of criteria.
	* The current version of the ESPD Service only supports a fixed number of yearly turnovers. 
	This will be improved in the future.
	

