[.text-left]
=== Economic and financial standing

The ''Economic Financial Standing'' category encompasses one group of subcategories and four criteria
with specific data structures:

	* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.*: ''General yearly turnover'',  ''Average yearly turnover'', ''Specific yearly turnover'', ''Specific average turnover''; 
	* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.FINANCIAL_RATIO: it currently refers to ''Financial ratio''
	* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE.PROFESIONAL: it currently refers to ''Professional risk indemnity insurance'';
	* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SET_UP: ''Set up of economic operator'';
	* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENTS: ''Other economic or financial requirements''.
	
The following subsections show the data structures and examples for these three groups of criteria related to economic and financial standing criteria.