[.text-left]
The following example, below, illustrates how this criterion is implemented. 

This XML piece, as for all the previous XML examples, was
generated by the https://webgate.acceptance.ec.europa.eu/espd/filter?lang=en[ESPD Service].


[source,xml]
.XML example for the criterion ''... Is the economic operator a sheltered workshop ...'' from the group CRITERION.OTHER.EO_DATA.*
----
<ccv:Criterion>
        <cbc:ID schemeID="CriteriaID" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">2043338f-a38a-490b-b3ec-2607cb25a017</cbc:ID>
        <cbc:TypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="1.0">CRITERION.OTHER.EO_DATA.SHELTERED_WORKSHOP</cbc:TypeCode>
        <cbc:Name>Procurement reserved</cbc:Name>
        <cbc:Description>Only in case the procurement is reserved: is the economic operator a sheltered workshop, a 'social business' or will it provide for the performance of the contract in the context of sheltered employment programmes?</cbc:Description>
        <ccv:RequirementGroup>
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">6febbe4a-e715-427c-a2b1-19cfabadaef0</cbc:ID>
            <ccv:Requirement responseDataType="INDICATOR">
                <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">7f18c64e-ae09-4646-9400-f3666d50af51</cbc:ID>
                <ccv:Response>
                    <ccv-cbc:Indicator>true</ccv-cbc:Indicator>
                </ccv:Response>
            </ccv:Requirement>
            <ccv:RequirementGroup pi="GROUP_FULFILLED.ON_TRUE">
                <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">a5e33369-e2b5-45f7-9969-ddb1c3ae17c8</cbc:ID>
                <ccv:Requirement responseDataType="PERCENTAGE">
                    <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">4e552658-d532-4770-943b-b90efcc9788d</cbc:ID>
                    <cbc:Description>What is the corresponding percentage of disabled or disadvantaged workers?</cbc:Description>
                    <ccv:Response>
                        <cbc:Percent>2.0</cbc:Percent>
                    </ccv:Response>
                </ccv:Requirement>
                <ccv:Requirement responseDataType="DESCRIPTION">
                    <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">e01d0929-c7a9-455a-aaf9-e1f7cd966336</cbc:ID>
                    <cbc:Description>If required, please provide details on whether the employees concerned belong to a specific category of disabled or disadvantaged workers?</cbc:Description>
                    <ccv:Response>
                        <cbc:Description>Physical Disabilities</cbc:Description>
                    </ccv:Response>
                </ccv:Requirement>
            </ccv:RequirementGroup>
        </ccv:RequirementGroup>
    </ccv:Criterion>
 ----
 
*NOTICE* that:
 
 	* There is only one group
 	* The INDICATOR is not a decision point, but is treated as one datum

 	
 	