[.text-left]
=== I.2 ESPD conformant solutions
The main objective of the ESPD documents is to reduce the administrative burden and lead to considerable simplification of participation in public procurement procedures for buyers and suppliers. In order to make full use of the ESPD concept, Member States (MS) and private sector companies (service providers) are developing software and on-line services to help contracting authorities and economic operators draft interoperable ESPD electronic documents. These solutions will reduce that burden by removing the need to produce a substantial number of certificates and documentation related to exclusion and selection criteria. This will answer to obstacles reported by many suppliers and especially SMEs.

For these software solutions to be interoperable they will have to conform to the indications set in this guide. 

The *http://wiki.ds.unipi.gr/display/ESPDInt/ESPD+International+Knowledge+Base[ESPD International Knowledge Base]* (ESPDint) is a consortium formed by Member States, Universities and private organisations the objectives of which are to develop (i) a formal specification for the *http://www.cenbii.eu/[CEN BII profile 56]* and ESPD requirements by DG GROW; and (ii) a software solution for the edition and exchange of ESPD electronic documents.The software solutions provided by the ESPDInt initiative refers to this XML instantiation guide. In turn, this ESPD-EDM XML implementation guide is aligned with the specification produced by the ESPDint initiative. Thus:

. Formal requirements introduced in this guide are taken from (and point at) the requirements specified in the document http://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.1.0#BIS41-ESPDV2.1-tbr070-010[_BIS 41 - European Single Procurement Document_]; whereas

. Formal definitions are taken from the http://wiki.ds.unipi.gr/display/VCD/4.3+ESPD-VCD+Domain+Vocabulary[_ESPD-VCD Domain Vocabulary_].