[.text-left]
*_Disclaimer:_* _the current documentation is not the final version, it is an ongoing task that will be ended up by the end of implementation task._ 

[.text-center]
=== I.2. ESPD-EDM

[.text-left]
As mentioned, there are two ESPD documents available:
[.text-left]
•	The *Request document*, which is used by Buyers to express the Exclusion and Selection criteria, as well as particular requirements, that the Economic Operators will need to fulfil in the context of a tender; 
•	The *Response document*, which is used by Economic Operators to answer the questions and provide references to evidences in response to the criteria and requirements expressed by the Buyer in the Request document.
Therefore, the ESPD Service is oriented to two main types of users:
•	Buyers, which are State, regional or local authorities, bodies governed by public law or associations formed by one or more such authorities or one or more such bodies governed by public law (as defined in Article 2 of the Directive);
•	Economic Operators, which are any natural or legal person or public entity or group of such persons and/or entities, including any temporary association of undertakings, which offers the execution of works and/or a work, the supply of products or the provision of services on the market (as defined in Article 2 of the Directive).
Economic Operators can play different roles (that are contemplated by the ESPD-EDM) within a procurement procedure:
•	*Sole Tenderer:* sole economic operator participating in the procurement procedure by itself; 
•	*Group Member:* In case of Consortium, Joint Venture or other type of groups, the economic operator can participate as a: 
o	*Group Leader:* the leader of the group; 
o	*Group Member (not leader)* of the group.
•	*Other entity (relied upon):* Entity on which the main contractor, the group or another subcontractor relies in order to meet the selection criteria;
•	*Other entity (not relied upon) or Subcontractor*: entity on which the main contractor, the group or another subcontractor does not rely in order to meet the selection criteria.


[.text-left]
The ESPD Request consists of:
[.text-left]
•	*Part I:* Information concerning the procurement procedure and the Buyer or contracting entity, where the Buyer is required to provide information about publication, about the identity of the procurer and about the procurement procedure;
•	*Part III:* Exclusion grounds, where the Buyer is required to review the A: grounds relating to criminal convictions; B: Grounds relating to the payment of taxes or social security contributions; C: Grounds relating to insolvency, conflicts of interests or professional misconduct; and D: Purely national exclusion grounds that apply to the procurement procedure;
•	*Part IV:* Selection criteria, where the Buyer must indicate which selection criteria will be applied regarding A: Suitability; B: Economic and financial standing; C. Technical and professional ability; and D: Quality assurance schemes and environmental management standards
•	*Part VI:* Concluding statements.
Part II and Part V are not available in the ESPD Request since they apply only to the Response document.
[.text-left]
The ESPD Response consists of:
[.text-left]
•	*Part I:* Information concerning the procurement procedure and the Buyer or contracting entity, where the Economic Operator is required to identify the ESPD Request to which is creating a response, by providing information about publication, about the identity of the procurer and about the procurement procedure;
•	*Part II:* Information concerning the economic operator, where the Economic Operator is required to provide A: Information about the economic operator; B: Information about representatives of the economic operator; C: Information about reliance on the capacities of other entities; and D: Information concerning subcontractors on whose capacity the economic operator does not rely.
•	*Part III:* Exclusion grounds, where the Economic Operator is required to review A: grounds relating to criminal convictions; B: Grounds relating to the payment of taxes or social security contributions; C: Grounds relating to insolvency, conflicts of interests or professional misconduct; and D: Purely national exclusion grounds, and to answer individually to each exclusion ground;
•	*Part IV:* Selection criteria, where the Economic Operator should only provide information where the selection criteria concerned have been required by the Buyer or contracting entity in the relevant notice or in the procurement documents referred to in the notice, regarding A: Suitability; B: Economic and financial standing; C. Technical and professional ability; and D: Quality assurance schemes and environmental management standards;
•	*Part V:* Reduction of the number of qualified candidates, where the Economic Operator should only provide information where the Buyer or contracting entity has specified the objective and non-discriminatory criteria or rules to be applied in order to limit the number of candidates that will be invited to tender or to conduct a dialogue within a two-phased procedure;
•	*Part VI:* Concluding statements, where the Economic Operator declares that the information stated under Parts II - V is accurate and correct, that is able to provide the certificates and other forms of documentary evidence referred to it, and consents to grant access to documents supporting the information which has been provided in the ESPD to the Buyer.
[.text-left]
The information required to Economic Operators when fulfilling a Response document will depend on their role, as shown in the table below:

|===	
Table 1 |Sole Tenderer / Group Leader |Group Member |Other Entity relied upon |Subcontractor


|*Part I*				
Identify ESPD request and other procurement information	

|X	|X	|X	|X

|*Part II*				

Information about the economic operator	|X	|X	|X	|X

|Information about representatives of the economic operator	  |X	|X	|X	|X

|Information about reliance on the capacities of other entities	|X	|  | | 	

|Information concerning subcontractors on whose capacity the economic operator does not rely	|X	| | |		

|*Part III*				
Exclusion grounds	|X	|X	|X	|X

|*Part IV*				
Selection Criteria	| |X	|X	|X	

|*Part V*			
Reduction of the number of qualified candidates	|Adhoc	|Adhoc	|Adhoc	|

|*Part VI* Concluding statements	|X	|X	|X	|X
|===

_Table 1: Information to provide in the ESPD Response per role_

[.text-left]
It is not necessary for Buyers and Economic Operators to create a new ESPD document for each procedure. Instead, it is possible to re-use an ESPD in different procurement procedures, facilitating the tasks of users.
