[.text-center]
=== I.3. ESPD Business process map
[.text-left]
The ESPD profile realises the ESPD process, which is part of the qualification process in the pre-awarding process area. This is represented in the diagram below:

<<image>>ESPD Business Process (source ESPDint)

[.text-left]
The roles that participate as business partners in this process are mainly:

<<image>>Figure 2. Actors in the ESPD business process (source ESPDint)

[.text-left]
The Buyer (or ESDP requester) normally a governmental organisation like a contracting authority who prepares the procurement procedure requirements in a ESPD Request (electronic document QualificationApplicationRequest); and The Supplier (i.e. economic operators), or ESPD Providers acting on behalf of them, who answer in an ESPD Response (electronic document QualificationApplicationResponse).


[.text-left]
This other figure below shows the choreography of the business process implemented by the profile. The choreography of business collaborations defines the sequence of interactions when the profile is run within its context

<<image>>
Figure 3. ESPD business process coreography (source ESPDint)