[.text-left]
=== I.5 Forward compatibility

In order to ensure compatibility between regulated ESPD versions 1 and 2, this distribution provides a conversion solution to facilitate the generation of ESPD REGULATED Request and Response XML documents. Beware that *this is not the case for Self-contained ESPDs*: given that Self-contained ESPDs may contain requirements and richer structures that are not present in the Regulated ESPD the compatibility is not possible for all the elements of the version 2.
 
The development and testing of the previous version 1.0.2 by Member States and other Stakeholders revealed the need for improving some minor details relating the taxonomy of criteria. *The data model and XSD schemas was not modified whatsoever*. Hence a new minor editorial *_ESPD version 1.0.3_* of the criteria is distributed jointly with this distribution package that is *_compliant with the REGULATED ESPD-EDM v.2.0.2_*:  

** The updated criteria taxonomy v1.0.3 can be found here: link: ./dist/cl/ods/ESPD-CriteriaTaxonomy(Data-Structures)_V1.0.3.ods[Criteria Taxonomy (Data Structures)].  
** To track those few changes introduced in v1.0.3 you can use this link:./dist/cl/ods/CriteriaTaxonomyV1.0.3_CHANGE_LOG.ods[Track-Change file "CriteriaTaxonomyV1.0.3_CHANGE_LOG.ods"].
** The folder link:./dist/xslt/Versions_1-2_Mapping contains the stylesheets making possible to transform XML documents from version 1.0.3 into version REGULATED ESPD Request and Response v.2.0.2. See "Annex II: Converting from version 1.0.3 into 2.0.2" for details on how this conversion works. 

Mapping a Regulated ESPD (or an ESPD 1.0.2) into a V2.0.2 Self-contained ESPD is yet possible for a large part of its components. This means that software applications could somehow "pre-fill" a Self-contained ESPD taking as the input a 1.0.2 or a 2.0.2 Regulated ESPD and leave the "extended" requirements and fields empty (i.e. "forward compatibility" is to some extent possible).

In order to facilitate developers map between one version into the other and vice-versa, this guide includes a link:./dist/doc/UBL2.2-ESPD1.02_Mapping.ods[spreadsheet] with the correspondences between the elements of the ESPD-EDM V1.0.3 and ESPD-EDM V2.0.2.
