[.text-center]
=== II.1. Who uses the ESPD?

[.text-left]
The ESPD have benefits for different profiles of users:  

*Buyers (Contracting Authorities or Entities)*
[.text-left]
The buyers can use the ESPD in their benefit when starting a procurement procedure:
[.text-left]
* Create and re-use ESPDs for new procedures
* Harmonise and optimise the use of selection criteria for procedures
* Reduce the number of qualified candidates
* Enable cross-border checking of data

[.text-left]
*Companies*
[.text-left]
The businesses aiming to participate in procurement procedures independently of their country of origin. These stake holders can use and benefit in the following aspects: 
[.text-left]
* The eESPD will act as a "business passport” for companies bidding for tenders anywhere in the EU
* Create and re-use an eESPD for future procedures - only to update information that has changed
* Facilitate cross-border participation in public procurement procedures, increasing competition and supporting economic growth
* Provide transparency and more clarity about requested evidences from CAs
* Ensure compliance with national and EU rules

[.text-left]
*Service Providers*
[.text-left]
Also, these companies developing provision of services can be using the ESPD and getting benefits of it: 
[.text-left]
* Guide buyers and businesses in using the eESPD;
* Check automatically exclusion grounds and selection criteria in storing this information for businesses;
* Help buyers to evaluate eESPDs automatically (eEvaluation);
* Link eESPD to national registers and aggregators to access data from official sources;
* Provide a knowledge base for selection criteria for specific procedures.
