[.text-left]
=== II.2 Adoption of UBL-2.2

One important difference of this new version in respect of the previous versions of the ESPD-EDM is that the XSD Schemas used for the XML implementation of the Request and Response documents have been developed by OASIS UBL (ISO/IEC 19845) in close collaboration with the European Commission (EC).

The results of such collaboration have been included in the version 2.2 of UBL which is actually under revision and is to be formally adopted by the end of 2017.s

UBL, developed by the Organization for the Advancement of Structured Information Standards, is a royalty-free library of standard electronic Extensible Markup Language (XML) business documents. It is designed to plug directly into existing business, legal, auditing, and records management practices, and to operate within a standard business framework such as ISO 15000 (ebXML) to provide a complete, standards-based infrastructure that can extend the benefits of existing Electronic Data Interchange (EDI) systems to businesses of all sizes.

UBL is also included in the European Catalogue  (https://joinup.ec.europa.eu/community/european_catalogue/description[EUcat]): the rules on European standardisation allow the European Commission to identify information and communication technology (ICT) technical specifications - that are not national, European or international standards - to be eligible for referencing in public procurement.

UBL is a specific used in some Member States and by the EU institutions, namely the European Commision. UBL is also referred to in the Commission implementing decision of 31 October 2014 on the identification of Universal Business Language version 2.1 for referencing in public procurement  (http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014D0771&from=EN[COM Decision 2014/771/EU]).

Technical resources and tools are freely available for its use and repurpose by the Member States, Service Providers, EC and any other stakeholders. Especially interesting and largely used are the open source tools and artefacts referred by the OASIS UBL-TC, such as https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=codelist[Genericode] , http://schematron.com/[ISO Schematron]  and http://www.cranesoftwrights.com/[Crane Softwright]. 