[.text-left]
=== II.3 UBL-2.2 Documents and libraries

UBL-2.2 defines thousands of different information components and dozens of documents. This guide describes and illustrates only those elements from UBL-2.2 that are actually used by the eESPD. Thus the ESPD-EDM reuses only a small set of those components and only 2 documents: `*QualificationApplicationRequest*` (for the ESPD Request) and `*QualificationApplicationResponse*` (for the ESPD Response).

UBL-2.2 distributes two sets of XSD schemas: see folders `xsd` and `xsdrt` of the UBL distribution package. The `xsd` folder contains the schemata fully documented (with dictionary entry names, definitions, examples, etc.); whilst the `xsdrt` schemata are not likewise documented and are frequently used in production environments (*rt* stands for “run-time”).

The previous ESPD-EDM versions used its own libraries where Criterion and Evidence-related aggregate and components were defined (components prefixed with `cac-ccv:`, `cac-cev`, `cbc-ccv` and `cbc-cev`). 

This new version uses components exclusively defined by UBL-2.2 in two main libraries: Common Aggregate Components (file `UBL-CommonAggregateComponents-Pre-award.xsd`) and Common Basic Components (`UBL-CommonBasicComponents-Pre-award.xsd`). 

The usual prefix used to identify Common Aggregate Components is `cac:`. The prefix for Common  Basic Components is `cbc:`.

All the materials developed by UBL-2.2 Technical Committee can be accessed here: https://www.oasis-open.org/committees/document.php?document_id=60554.

Beware also that the *UBL-2.2 namespaces* used for the two main documents in ESPD (and for the rest of UBL-2.2 XSD
schemas are *now final*, since June 2018. Thus:

. The ESPD-EDM v2.1.1 XSD Schemas use the namespace `_urn:oasis:names:specification:ubl:schema:xsd:*_`, whilst
. The previous ESPD-EDM versions 2.0.* used the namespace `_urn:X-test:UBL:Pre-award:*_`.

