

==== XML Example

This fragment of XML shows how the compulsory attributes are used for the some of the root elements of an ESPD Request document.

[source,xml]
----
<cbc:UBLVersionID schemeAgencyID="OASIS-UBL-TC">2.2</cbc:UBLVersionID> <--1-->

<cbc:ID schemeAgencyID="DGPE">ESPDREQ-DGPE-3b5755dfb8</cbc:ID> <--2-->

<cbc:UUID schemeID="ISO/IEC 9834-8:2008" schemeAgencyID="EU-COM-GROW" schemeVersionID="4">0fddbf2d-1e33-4267-b04f-52b59b72ccb6</cbc:UUID> <--3-->

<cbc:ContractFolderID schemeAgencyID="DGPE">PP.20170419.1024-9</cbc:ContractFolderID> <--4-->

<cbc:VersionID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">1.0</cbc:VersionID> <--5--> 

<cbc:ProcedureCode listID="ProcedureType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">V</cbc:ProcedureCode> <--6-->

<cbc:QualificationApplicationTypeCode listID="QualificationApplicationType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">SELFCONTAINED</cbc:QualificationApplicationTypeCode> <--7-->
----
<1> The Agency responsible for the maintenance of the UBL versioning is the OASIS UBL Technical Committee
<2> The identifier for this document was issued by the a Spanish Central Government Directorate identified as 'DGPE'
<3> The UUID follows the ISO/IEC Scheme 9834-8:2008 Version 4 and was generated by the European Commission's Directorate General GROWTH (DG GROW)
<4> The reference number used to identify to which procurement procedure this ESPD document belongs (PP.20170419.1024-9) has been supplied by the Spanish Directorate DGPE
<5> Generic information,such as the content version ID, use always by default the "EU-COM-GROW" Agnecy ID. Notice that the other additional attributes may be also used, as in this example.
<6> Notice that for Codes, the three compulsory attributes are specified. For these codes. In this example the attributes are specifying that the code is maintained by DG GROW in a list named `ProcedureType` and that the version that has been used is version `2.0.2`which is distributed jointly with this ESPD-EDM V2.0.2 specification (in the link:./dist[distribution package]).
<7> Beware that the codes may be numbers, text or combinations of both. These code labels are the ones that are specified in the codelist spreadsheets and XML Genericode files distributed jointly with this specification (in the folder `dist/cl` of the link:./dist[distribution package].
