
==== XML Example

The XML snippet below illustrates how to use the `cac:AdditionalDocumentReference` in the ESPDRequest XML document to refer to a Contract Notice published in TED and on a national procurement board:

[source,xml]
----
<!--- Root elements eliminated for the sake of brevity -->

<!-- Reference to the Contract Notice published on TED -->
	<cac:AdditionalDocumentReference>
		<cbc:ID schemeAgencyID="EU-COM-OP">2017/S 142-293520</cbc:ID> <--1-->
		<cbc:DocumentTypeCode listID="DocRefContentType" listAgencyID="EU-COM-GROW" listVersionID="2.1.0">TED_CN</cbc:DocumentTypeCode> <--2-->
		<cac:Attachment>
			<cac:ExternalReference>
			<!-- Beware XML URI fields may require encoded URLs -->
			<cbc:URI schemeAgencyID="EU-COM-OP">http://ted.europa.eu/udl?uri%3DTED:NOTICE:293520-2017:TEXT:EN:HTML%026src%3D0</cbc:URI> <--3-->
			<cbc:FileName>Spain-Zamora: Repair and maintenance services</cbc:FileName>
			<cbc:Description>Repair and maintenance services. Real estate services.</cbc:Description> <--4-->
			<cbc:Description>293520-2017</cbc:Description>	<--5-->			
			</cac:ExternalReference>
		</cac:Attachment>
	</cac:AdditionalDocumentReference>

	<!-- Reference to the Contract Notice published on the Spanish Central Government eTendering Platform -->
	<cac:AdditionalDocumentReference>
		<!-- Contract Notice publishied on the Spanish Central eTendering Platform "PLACE" Plataforma de Contratación del Sector Público -->
		<cbc:ID schemeAgencyID="PLACE">3.17/20830.0160</cbc:ID> <--6-->
		<!-- Contract Notice (CN) published on a National Government Official Journal -->
		<cbc:DocumentTypeCode listID="DocRefContentType" listAgencyID="EU-COM-GROW" listVersionID="2.1.0">NOJCN</cbc:DocumentTypeCode> <--7-->
		<cac:Attachment>
			<cac:ExternalReference>
			<!-- Beware XML URI fields may require encoded URLs -->
			<cbc:URI schemeAgencyID="PLACE">https://contrataciondelestado.es/wps/portal/!ut/p/b1/pY_LDoIwEEW_hQ8wM5S2wJKH5REUVEDbjenCGI3Axvj9gmFrMXF2Nzkncy8okDahHD2XMAYnUL1-3a76eRt6_Ziy4me6LqNIpAS9gxMjKeKm4ekUyQhIA5AQo5-w2WdORNu8rfghSxCzVMRFY7NR57_5-OUC_K-_t9j_CMqMkBkwTfwAhg3bdOguIEfMPQftehdkvoNluB8f5dWmrhJiI3KoQYbhEkYnLA-hUw8hhJ_dqV7pwLLeHJySpA!!/</cbc:URI>
			<cbc:FileName>Suministro y transporte de balasto</cbc:FileName>
			<cbc:Description>Suministro y transporte de balasto para el tramo Zamora — Pedralba de la Línea de Alta Velocidad Olmedo — Lubián — Ourense. Subtramo 8.</cbc:Description>
			</cac:ExternalReference>
		</cac:Attachment>
	</cac:AdditionalDocumentReference>
</QualificationApplicationRequest>
----
<1> For TED Notices you must use the Publications Office Official Journal Supplement number in its original format [][][][]/S	 [][][]-[][][][][][], e.g. 2017/S 142-293520. Notice that the schemeAgencyID is `EU-COM-OP` (OP standing for 'Publications Office').
<2> The jurisdiction scope of this document is typified in the Code List `DocRefContentType` (see file `dist/cl/CodeLists-V2.1.0` in the distribution package). *Beware that the name and content of this Code List has changed from the previous ESPD-EDM version 1.0.2*. The code `TED_CEN`means 'Contract Notice published in TeD (Official Journal of the European Publications Office)'.
<3> The ESPD documents never embed the actual content. Rather the content is always referenced from its original source (alignment to the Once-Only-Principle).
<4> The title of the CN has to be placed in the FileName field of the attachment. UBL does not provide a placeholder fo the title of the document.
<5> In the case of publication on the TED, at ESPD Request preparation time, the procurer does not have yet the OJS number, but can receive a temporary CN identifier (*`Received Notice Number`*). To save this number in the DocumentReference component create two `cbc:Description` elements and use the second one to place this `Received Notice Number`. If you do not have a description for the CN then use a 'dummy' content for the first description, e.g. `<cbc:Description>_</cbc:/Description>`.
<6> Notice how the schemeAgencyID is used in this example to specify that the national Agency that created this reference to the national publication (e.g. "PLACE" to refer to the ID of the national electronic board where the CN was published). The pattern of the ID is the one created by the Spanish contracting authority.
<7> In this case the code `NOJCN` means 'Contract Notice (CN) published on a National Government Official Journal' (see file link:https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/cl/CodeLists-V2.1.0[CodeLists-V2.1.0]) in the distribution package.