
==== XML Example

In the example below the contracting authority has specified seven Lots, hence the seven instances of `ProcurementProjectLot` component. 

[NOTE]
====
*Convention*: Lots should always be identified with a sequential number, as in the examples: Lot1, Lot2, ... Lot7.
====

Observe that the data is 




.Lots (*SEL-CONTAINED* ESPD)
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<QualificationApplicationRequest xmlns="urn:X-test:UBL:Pre-award:QualificationApplicationRequest" xmlns:cac="urn:X-test:UBL:Pre-award:CommonAggregate" xmlns:cbc="urn:X-test:UBL:Pre-award:CommonBasic" xmlns:espd="urn:com:grow:espd:2.0.2"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:X-test:UBL:Pre-award:QualificationApplicationRequest ../xsdrt/maindoc/UBL-QualificationApplicationRequest-2.2-Pre-award.xsd">
	<cbc:UBLVersionID schemeAgencyID="OASIS-UBL-TC">2.2</cbc:UBLVersionID>
	<cbc:CustomizationID schemeAgencyID="CEN-BII" schemeVersionID="3.0">urn:www.cenbii.eu:transaction:biitrdm070:ver3.0</cbc:CustomizationID>
	<cbc:ProfileID schemeAgencyID="CEN-BII">41</cbc:ProfileID>
	<cbc:ID schemeAgencyID="DGPE">ESPDREQ-DGPE-3b5755dfb8</cbc:ID>
	<cbc:CopyIndicator>false</cbc:CopyIndicator>
	<cbc:UUID schemeID="ISO/IEC 9834-8:2008" schemeAgencyID="EU-COM-GROW" schemeVersionID="4">0fddbf2d-1e33-4267-b04f-52b59b72ccb6</cbc:UUID>
	<cbc:ContractFolderID schemeAgencyID="DGPE">PP.20170419.1024-9</cbc:ContractFolderID>
	<cbc:IssueDate>2017-12-31</cbc:IssueDate>
	<cbc:ProcedureCode listID="ProcedureType" listAgencyName="EU-COM-GROW" listVersionID="2.0.2">1</cbc:ProcedureCode>
	<cbc:QualificationApplicationTypeCode listID="QualificationApplicationType" listAgencyName="EU-COM-GROW" listVersionID="2.0.2">SELFCONTAINED</cbc:QualificationApplicationTypeCode>
	<!-- Contracting body data left empty for the sake of brevity -->
	<cac:ContractingParty> <cac:Party/></cac:ContractingParty>
	<--1-->	
	<!--- This procurement procedure is divided into 7 Lots -->
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot1</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot2</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot3</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot4</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot5</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot6</cbc:ID></cac:ProcurementProjectLot>
	<cac:ProcurementProjectLot><cbc:ID schemeAgencyID="EU-COM-GROW">Lot7</cbc:ID></cac:ProcurementProjectLot>	
	
<--2-->
<!-- Additional information about the Lots supplied by the contracting authority -->
	<!-- Criterion:CA Lots -->
	<cac:TenderingCriterion>
		<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">6a21c421-5c1e-46f4-9762-116fbcd33097</cbc:ID>
		<cbc:CriterionTypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">CRITERION.OTHER.CA_DATA.LOTS_SUBMISSION</cbc:CriterionTypeCode>
		<cbc:Name>CA Lots</cbc:Name>
		<cbc:Description>Please take into account the following requirements regarding the lots of this procurement procedure:</cbc:Description>
		<cac:TenderingCriterionPropertyGroup>
			<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">03cff8d1-4d22-4435-82fa-d6361af84be6</cbc:ID>
			<cbc:PropertyGroupTypeCode listID="PropertyGroupType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">ON*</cbc:PropertyGroupTypeCode>
			<cac:TenderingCriterionProperty>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">847829aa-e70a-45e1-b4d3-e11c3ffaf7a0</cbc:ID>
				<cbc:Description>Tenders may be submitted for</cbc:Description>
				<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">REQUIREMENT</cbc:TypeCode>
				<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">CODE</cbc:ValueDataTypeCode><--3-->
				<!-- Compulsory use of the Publications Office Code List BidType -->
				<cbc:ExpectedCode listID="BidType" listAgencyID="EU-COM-OP" listVersionID="1.0">LOT_ALL</cbc:ExpectedCode> <--4-->
			</cac:TenderingCriterionProperty>
			<cac:TenderingCriterionProperty>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">dceddc28-0ac8-471b-b954-c376a862ea30</cbc:ID>
				<cbc:Description>Maximum number of lots</cbc:Description>
				<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">REQUIREMENT</cbc:TypeCode>
				<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">QUANTITY_INTEGER</cbc:ValueDataTypeCode>
				<cbc:ExpectedValueNumeric>5</cbc:ExpectedValueNumeric>
			</cac:TenderingCriterionProperty>
			<cac:TenderingCriterionProperty>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">4b710530-abea-4ed0-b3fb-f324919c2d62</cbc:ID>
				<cbc:Description>Maximum number of lots that may be awarded to one tenderer</cbc:Description>
				<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">REQUIREMENT</cbc:TypeCode>
				<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">QUANTITY_INTEGER</cbc:ValueDataTypeCode>
				<cbc:ExpectedValueNumeric>1</cbc:ExpectedValueNumeric>
			</cac:TenderingCriterionProperty>
		</cac:TenderingCriterionPropertyGroup>
	</cac:TenderingCriterion> 
</QualificationApplicationRequest>

----
<1> This procedure is divided into 7 lots. Hence their automatic identification from Lot1 to Lot7.
<2> this Criterion has one group of properties containing a sub-group where the three requirements about the lots are actually specified: (i)The tenderers may submit tenders for the maximum number of lots; (ii) The Contracting Authority specifies a maximum number of 5 lots; and (iii) one tenderer can not win more than one lot. Notice that each element inside a criterion has a Universally Unique Identifier (UUID): these UUIDs are 'constant', meaning that they are maintained by DG GROW and need to be used compulsory as they were issued by DG GROW.
<3> A code has to be provided to specify whether the economic operator is allowed to submit a tender covering one lot only, more than one but not all, or all of them. 
<4> The value for the expected code (see bullet number 3) needs to be chosen amongst the values of the Code List `BidType`.