
==== XML example

This fragment of XML shows how to supply data in a Extended ESPD Request XML document describing the procurement procedure.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<QualificationApplicationRequest xmlns="urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationRequest-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:espd="urn:com:grow:espd:2.1.1"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationRequest-2 ../xsdrt/maindoc/UBL-QualificationApplicationRequest-2.2.xsd">
	<cbc:UBLVersionID schemeAgencyID="OASIS-UBL-TC">2.2</cbc:UBLVersionID>
	<cbc:CustomizationID schemeAgencyID="CEN-BII" schemeVersionID="3.0">urn:www.cenbii.eu:transaction:biitrdm070:ver3.0</cbc:CustomizationID>
	<cbc:ProfileID schemeAgencyID="CEN-BII">41</cbc:ProfileID>
	<cbc:ID schemeAgencyID="DGPE">ESPDREQ-DGPE-3b5755dfb8</cbc:ID>
	<cbc:CopyIndicator>false</cbc:CopyIndicator>
	<cbc:UUID schemeID="ISO/IEC 9834-8:2008" schemeAgencyID="EU-COM-GROW" schemeVersionID="4">0fddbf2d-1e33-4267-b04f-52b59b72ccb6</cbc:UUID>
	<cbc:ContractFolderID schemeAgencyID="DGPE">PP.20170419.1024-9</cbc:ContractFolderID>
	<cbc:IssueDate>2017-12-31</cbc:IssueDate>
	
	<!-- The type of procedure: OPEN stands for Open Procedure. See Code List 'ProcedureType' -->
	<cbc:ProcedureCode listID="ProcedureType" listAgencyName="EU-COM-OP" listVersionID="1.0">OPEN</cbc:ProcedureCode> <--1-->

	<cbc:QualificationApplicationTypeCode listID="QualificationApplicationType" listAgencyName="EU-COM-GROW" listVersionID="2.1.1">EXTENDED</cbc:QualificationApplicationTypeCode>
	
	<!-- Contracting body data left empty for the sake of brevity -->
	<cac:ContractingParty><cac:Party/>	</cac:ContractingParty>

	<!-- Extended ESPD Request. Data about the procurement procedure -->
	<cac:ProcurementProject>
		<cbc:Name>Spain-Aljaraque: Repair and maintenance services</cbc:Name> <--2-->
		<cbc:Description>Repair and maintenance services. Real estate services.</cbc:Description> <--3-->
		<cbc:ProcurementTypeCode listID="ProjectType" listAgencyID="EU-COM-OP" listVersionID="1.0">SERVICES</cbc:ProcurementTypeCode> <--4-->
		
		<!-- CPV for 'Repair and maintenance services'. -->
		<cac:MainCommodityClassification><cbc:ItemClassificationCode>50000000</cbc:ItemClassificationCode></cac:MainCommodityClassification> <--5-->
		<!-- CPV for 'Real estate services'. -->
		<cac:MainCommodityClassification><cbc:ItemClassificationCode>70000000</cbc:ItemClassificationCode></cac:MainCommodityClassification> <--6-->
	</cac:ProcurementProject>
</QualificationApplicationRequest>

----
<1> Use of the root element `cbc:ProcedureCode` to indicate that this is an 'Open procedure'. The code is 'OPEN' according to the OP's Code List `ProcedureType`.
<2> Compulsory element `cbc:Name`, used to specify the title of the procurement procedure. Use the same title as for the Contract Notice.
<3> Compulsory element `cbc:Description` used to describe shortly the procedure. Use the same description as for the Contract Notice.
<4> The procurement is of type 'SERVICES'. See OP's Code List `ProjectType`. No sub-type of services is specified. The contracting authority possibly decided that the 2nd. CPV was enough for that matter.
<5> First main CPV code '50000000' standing for 'Repair and maintenance services'.
<6> Additional CPV code '70000000' standing for 'Real estate services'.