==== Use of CAPTION

As explained in section link:#iv-6-data-structures[IV.6 Data Structures] (see from ''Table 25. Mapping between the
ESPD-EDM criterion data structure spread-sheets and the UBL-2.2 vocabulary ESDP-EDM Spread-sheet vocabulary'' on,
the term CAPTION is used in the Criteria Taxonomy data structures to inform software applications about the presence of
a text label. Applications could use it to label boxes containing groups of REQUIREMENT(s) or of QUESTION(s). But in general
software applications should know how to present the contents of the XML instances without having to recur to such resources
(see the ''Note for the future: eBusiness Documents should not convey Process Instructions'' just below).

A CAPTION is mapped to the UBL element cbc:TenderingCriterionProperty. This is the reason why the ESPD-EDM had to introduce an element
that, in the end, is quite ''dummy'': the UBL-2.2 specification requires that the first element of a GROUP or SUBGROUP is
has always to be a criterion property (an element `cac:TenderingCriterionProperty`).

For software applications, the implication can be reduced to a very simple rule: *when encountering a `cac:TenderingCriterionProperty`
which `cbc:TypeCode` value equals CAPTION just skip it!*
