== Release Notes

Dear ESPD implementation community,
Within this information note, we inform you about the release of ESPD EDM version 2.0.2 and the release of ESPD EDM version 1.0.3. A change to ESPD EDM version 1.0.3 was necessary to allow an easy conversion to version 2.0.2 (for both Request and Response documents.


=== The ESPD EDM version 2.0.2 is now released and contains only bugs (May 2018)

The ESPD EDM version 2.0.2 is now released and contains only bugs fixed on the basis of the received comments on link:https://github.com/ESPD/ESPD-EDM/issues[GitHub] about versions 2.0.0 and 2.0.1. The release contains a definition of all relevant link:https://github.com/ESPD/ESPD-EDM/tree/2.0.2/docs/src/main/asciidoc/dist/doc[business rules] and corresponding link:https://github.com/ESPD/ESPD-EDM/tree/2.0.2/docs/src/main/asciidoc/dist/val/schematron[schematron files] to validate Regulate and Self-Contained ESPD Request and Response XML instances (including the validation of the criteria taxonomy). A corresponding link:http://isaitb2.northeurope.cloudapp.azure.com/espd/upload[TestBed for version 2.0.2] has been set up. Other major artefacts of this release are link:https://github.com/ESPD/ESPD-EDM/tree/2.0.2/docs/src/main/asciidoc/dist/xslt/Versions_1-2_Mapping[conversion style-sheets from version 1.0.3 to version 2.0.2]. The specifications for version 2.0.2 contain an updated link:https://github.com/ESPD/ESPD-EDM/tree/2.0.2/docs/src/main/asciidoc/dist[distribution] of the ESPD Exchange Data Model and include a corresponding link:https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html[implementation guideline] which clarifies the ESPD validation architecture in link:https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#annex-i-xml-validation[Annex I] and the conversion from ESPD EDM version 1.0.3 to ESPD EDM version 2.0.2 in link:https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#annex-ii-v1-0-3-to-v2-0-2-conversion[Annex II]. Also, the link:http://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.0.2[BIS 41 – ESPD version 2.0.2] was updated accordingly.

=== Release of criteria taxonomy file errata [ESPD EDM version 1.0.2] (May 2018)

A release of link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/CriteriaTaxonomy-V1.0.2-errata.ods[criteria taxonomy file errata (ESPD EDM version 1.0.2)] was necessary as the documentation on the criteria taxonomy was not updated to reflect the changes that were made to the Commission ESPD service up until July 2017. All corrections relate to the Criteria Data Flows and result in a revision of the link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/CriteriaTaxonomy-V1.0.2-errata.ods[criteria taxonomy for version 1.0.2] (revisions are marked within the sheet). No other change was done to the ESPD EDM version 1.0.2. The revisions should therefore have no impact on all current ESPD services based on v1.0.2 but we recommend using the revised criteria taxonomy to approve the correct Criteria Data Flows. 

=== Release of ESPD EDM version 1.0.3 (May 2018)
The release of ESPD EDM version 1.0.3 was necessary to ensure proper functioning of conversions from the earlier version to version 2.0.2. It contains few updates which will have a minor impact on current ESPD services based on version 1.0.2. A few elements of the revised criteria taxonomy file errata [ESPD EDM version 1.0.2] had to be changed and need to be updated in current ESPD services. The link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/ESPD-CriteriaTaxonomy-V1.0.3.ods[criteria taxonomy for version 1.0.3] introduces a few new UUIDs for exclusion criteria and a new numbering of the criteria (changes are marked within the sheet). In addition, the ESPD EDM version 1.0.3 mandates the use of link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.0.2.ods[new code lists] which are used in version 2.0.2.

We recommend to the ESPD implementation community to change directly to ESPD EDM version 2.0.2. If your goal is to ensure a proper conversion between version 1.0.2 and 2.0.2, you should implement the changes outlined in ESPD EDM version 1.0.3. 

* **Criteria**

Minor documentation fixes applied to version 1.0.2. The data model was not changed.  Only the documentation was updated to reflect the changes made until the July 2017 release of the Commission ESPD. It has no impact on current ESPD services based on v1.0.2. 

Beware that the Codes and UUIDs of the Criteria have not been modified between major versions: versions 1.0.2-1.0.3, and 2.0.0 to 2.0.2 REGULATED and SELF-CONTAINED do use the same codes and UUIDs for each Criterion. However some minor corrections have been applied to the UUIDs of some data structures. Thus the UUIDs for the structures "Is this information available electronically" are now consistent; in the case of Convictions a new UUID is now used for the group containing the question ""; etc. 

A new file containing the criteria, the taxonomy codes, the Criteria UUIDs and the each criterion data structures is now provided. This new spread-sheet mimics the distribution of data structures in v2.0.2 REGULATED, thus facilitating the comparison between the version 1.0.3 and version 2.0.x data structures. The update criteria taxonomy can be found here: link:https://github.com/ESPD/ESPD-EDM/tree/master/docs/src/main/asciidoc/dist/cl/ods/CriteriaTaxonomy-V1.0.3.ods[Criteria Taxonomy v1.0.3 (Data Structures)]. See also documentation about v2.0.2 chapter "I.5 Forward compatibility"). 

* **Code Lists**

To ensure compatibility between versions 1 and 2, version 1.0.3 uses the code lists used also in version 2.0.2. See the spread-sheets in link:https://github.com/ESPD/ESPD-EDM/tree/master/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.0.2.ods[ESPD-CodeLists-V2.0.2.ods], and the Genericode *.gc files in https://github.com/ESPD/ESPD-EDM/tree/master/docs/src/main/asciidoc/dist/val/schematron/common/gc[V2.0.2 Genericode files], which also includes a Genericode file for the link:https://github.com/ESPD/ESPD-EDM/tree/master/docs/src/main/asciidoc/dist/val/schematron/common/gc/CriteriaTaxonomy.gc[Criteria Taxonomy]. 
  
=== Outlook: Release of ESPD EDM version 2.0.3 (foreseen October 2018)
In order to support the ESPD implementation community in their efforts to establish ESPD services for version 2.0.x, we have planned another review period which will result in the release of ESPD EDM version 2.0.3 planned for the 30th of September. The release will concentrate on the removal of errors, improvements and editorial aspects. It is not planned to process any request for new features in this release. Please submit any issues on the GitHub before 31st of August so that we can process them. We are looking forward to receiving your link:https://github.com/ESPD/ESPD-EDM/issues[issues and comments on GitHub] in order to improve the overall ESPD specifications. 
For further project information please visit our link:https://github.com/ESPD/ESPD-EDM[GitHub] repository.

For further project information please visit our link:https://github.com/ESPD/ESPD-EDM[GitHub] repository.

I would like to use this chance to thank the CEF consortium ESPDint team for the great support in maintaining the ESPD data model. Without them it would have been much harder and they did in on top of their CEF engagement.  

Best regards,

*Marc-Christopher Schmidt*

