
=== V.2 Contributions

==== Related information requirements

See formal requirements related to exclusion grounds criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-009[_tbr070-009_], http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-004[_tbr070-004_], and http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-013[_tbr070-013_].

==== Differences between Regulated and Self-contained

. The *SELF-CONTAINED* version the XML instances can keep the national sub-criteria defined by the MS in  e-Certis;

. In the *SELF-CONTAINED* version the contracting authority can specify the minimum debt an economic operator can  maintain related to unpaid taxes or social security contributions.

. For both *REGULATED* and *SELF-CONTAINED*, the category ''Contributions'' encompasses two criteria with identical data structures:


** CRITERION.EXCLUSION.CONTRIBUTIONS.*: ''payment of taxes'' and ''social security contributions''.

