
=== V.9 Purely national criteria


==== Related information requirements

See formal requirements related to exclusion grounds criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-009[_tbr070-009_], http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-004[_tbr070-004_], and http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-013[_tbr070-013_].

Ohter requirements related specifically to purely national criteria are:

[cols="<1,<4"]
|===
|*REQUIREMENT*|The Member State must be able to specify in e-Certis individual national criteria, and the economic operator must be able to answer *to each individual purely national exclusion grounds criterion*. 
|===

[cols="<1,<4"]
|===
|*REQUIREMENT*|For the purely national exclusion grounds that have evidences related in e-Certis, the required evidences should be displayed. When the criterion has no related evidences, the text "No evidence required for this criterion" should be displayed. Per each national criterion the EO needs to be able to provide one or more evidences.
|===

These two requirements are introduced by the new Self-contained ESPD-EDM V2.0.2. Therefore you will see that there is an  essential difference between the Regulated and the Self-contained ESPDs.


==== Differences between Regulated and Self-contained

. The *SELF-CONTAINED* version the XML instances can keep the national sub-criteria defined by the MS in  e-Certis;

. The data structure for the *SELF-CONTAINED* versions is quite different from the *REGULATED* due to the new information requirements requested by the Membere States. See the sub-sections below on *Regulated purely national* and *Self-contained purely national* criteria below for details on the differences. The classification code fore this criterion is:

** CRITERION.EXCLUSION.NATIONAL.OTHER



