
=== VI.2 Average turnovers

==== Related information requirements

See formal requirements related to 'Turnover' criteria for the Self-contained ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-008[_tbr070-008_]


==== Differences between Regulated and Self-contained

. For the *SELF-CONTAINED average yearly average turnovers*, the contracting authority cna specify, for a specific procurement procedure:

** Period (“Start Date” and “End Date”) encompassing the yearly turnovers for which the average is to be calculated;
** “Minimum amount” for which the EO’s average yearly turnover must equal or be greater;
** the “Currency” of the minimum amount.

. For the *SELF-CONTAINED average yearly turnover*, the contracting authority can specify, for a specific procurement procedure:

** The “Number of fiscal years” for which the economic operator will have to provide turnovers; e.g. the last 5 years;
** the "CPVs” (Common Procurement Vocabulary codes)", with one or several CPVs to indicate the activities that were developed during those fiscal years for that Turnover. The CA could be able to select the CPV codes from a pop-up window with the whole CPV structure. Both the CPV code and the “Business domain description” could be displayed, both in the pop-up window (in order to facilitate the selection of the codes to be included in the ESPD) and in the ESPDResponse;
** The “Minimum amount” expected from the economic operator, for which each specific yearly turnover must equal or be greater;
** the "Currency".
