
=== VI.2 Suitability

==== Related information requirements

See formal requirements related to 'Suitability' criteria for the Extended ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.1.0#tbr070-003[_tbr070-003_]

==== Differences between Basic and Extended

. In the *Basic*, the CA is able to check the selection criteria regarding Suitability that apply to a particular procurement procedure, but cannot provide the particular information required to the EO for each criteria.

. In the *Extended*, the CA is able to specify the name of the register or the organisation the EO must be part of, and the URL. Additionally, the CA can specify Lots.

. For both models (*Basic* and *Extended*), the category ''Suitability'' is split into covers two groups of different data structures with these classification codes:

** One data structure for two types of ''enrolments''(''Enrolment in a relevant professional register'' and ''Enrolment in a trade register''), and
** Another data structure for two suitabilities related to ''service contracts'' (''For service contracts: authorisation of particular organisation needed'' and
''For service contracts: membership of particular organisation needed'').

