
=== VI.2 Yearly turnovers


==== Related information requirements

See formal requirements related to 'Turnover' criteria for the Self-contained ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-008[_tbr070-008_]


==== Differences between Regulated and Self-contained

. The *REGULATED* version expects a constant amount of groups of properties made of Amount, Start Date, End Date. The ESPD Service, for instance, expects *general or specific yearly turnovers* for the five past years. Thus, being the current year 2017, the ESPD Service generates a view for the economic operator with fields for 2016, 2015, 2014, 2013 and 2012. See mock-up below for the Regulated version of the general and specific yearly turnovers.

. In the new *SELF-CONTAINED* version the contracting can specify *the number of the past recent years* for which it will require Turnovers, and also *the minimum amount* it expects from the economic operator. This applies to both the *general yearly turnover* and the *specific yearly turnover*. The economic operator should only see the same number of groups of fields 'amount + period' than the number of minimum amounts the contracting authority required.  



   
  