
=== VI.3 Turnovers

==== Related information requirements

See formal requirements related to 'Turnover' criteria for the Extended ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-008[_tbr070-008_]


==== Differences between 'general and specific' and 'yearly and average' turnovers ====

. General turnover refers to the general turnover of the economic operator in a period of years and regardless of the nature of the contract, normally the last three or five years (as required in the contract documents or the ESPD).

. Specific turnovers refer to the turnover of the economic operator resulting from the activity of the economic operator in the business area covered by the contract;

. As far as the data structures are concerned, they can be classified in two groups 'yearly' and 'average':

** For general and specific yearly turnovers the economic operator specifies a turnover amount (and currency) per year, e.g. one amount for 2016, one amount for 2015, one amount for 2014, etc.

** For general and specific average turnovers, given the *n* last years (specified in the ESPD, notices or procurement documents) the economic operator adds all the yearly turnovers of those *n* years, divides the sum by *n* and provides the resulting amount.

** The classification codes for the different turnovers are:

*** (Yearly) CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.GENERAL_YEARLY, CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY;

*** (Average) CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.AVERAGE_YEARLY, CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY 


==== Differences between Basic and Extended turnovers

. The *Basic* ESPD expects a constant amount of groups of properties made of Amount, Start Date, End Date. The ESPD Service, for instance, expects *general or specific yearly turnovers* for the five past years. Thus, being the current year 2017, the ESPD Service generates a view for the economic operator with fields for 2016, 2015, 2014, 2013 and 2012. See mock-up below for the Basic version of the general and specific yearly turnovers.

. In the *Extended*:

** For the *general yearly turnover* the contracting authority can specify *the number of the past recent years* for which it will require Turnovers, and also *the minimum amount* it expects from the economic operator. The economic operator should only see the same number of groups of fields 'amount + period' than the number of minimum amounts the contracting authority required.

** For the *average yearly turnover* the contracting authority can specify *the number of fiscal years * (“QUANTITY_INTEGER”) encompassing the yearly turnovers for which the average is to be calculated; the *minimum amount* for which the EO’s average yearly turnover must equal or be greater; and the *currency*.
  
** For the *specific yearly turnover* the contracting authority can specify the *number of fiscal years* for which the EO will have to provide turnovers (e.g. last 5 years); the *CPVs*, with one or several Common Procurement Vocabulary codes to indicate the activities that were developed during those fiscal years for that Turnover. The CA could be able to select the CPV codes from a pop-up window with the whole CPV structure. Both the CPV code and the “Business domain description” could be displayed, both in the pop-up window (in order to facilitate the selection of the codes to be included in the ESPD) and in the ESPDResponse; the *Minimum amount* expected from the EO, for which each specific yearly turnover must equal or be greater; and the *currency*.

** For the *specific average turnover* the contracting authority can specify the *number of the past recent fiscal years* for which the EO will need to provide the Average Turnover; e.g. last 3 years; the *CPVs*, with one or several Common Procurement Vocabulary codes to indicate the activities that were developed during those fiscal years for that Turnover; the *minimum amount* expected from the EO, for which the EO’s average yearly turnover must equal or be greater; and the *currency*.






   
  