
=== VI.4 Financial ratios

==== Related information requirements

See formal requirements related to 'Turnover' criteria for the Self-contained ESPD in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)], and more specifically the requirement http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916#tbr070-013[_tbr070-013_]

==== Differences between Regulated and Self-contained

. The *REGULATED* version expects the economic operator to introduce a numeric value for the ratio (e.g. 0.7, 1.2, etc.) and a description explaining the meaning (the type of ratio) of this numeric value;

. In the *REGULATED* version the possibility of adding more than one ratio is given to the economic operator;

 . In the *SELF-CONTAINED* version the possibility of adding more than one ratio is given to the contracting authority;

. The *SELF-CONTAINED* version instead allows the contracting authority:

** To specify the number of the past recent years for which it will require Ratios;
** To specify one of the codes defined by BACH to specify the type of the ratio (see https://www.bach.banque-france.fr/[BACH Banque France], and link:./dist/cl/ods/ESPD-CodeLists-V2.0.1.ods[FinancialRatioType]);
** May specify a minimum requirement (the economic operator must provide a ratio above this minimum requirement).

. The *SELF-CONTAINED* version expects the economic operator to introduce only the value of the ratio, which must be equal or greater than the minimum requirement specified by the contracting authority (if any was specified). 

. The data structures of *REGULATED* and *SELF-CONTAINED* are different. See the sub-sections below about the Regulated financial ratio and the Self-contained financial ratio for details. There is only one criterion under the category "financial ratio" and it is classified with the code:

	** CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.FINANCIAL_RATIO

. The *SELF-CONTAINED* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis regarding this criterion.



