
=== VI.6 Other economic or financial requirements

==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Regulated and Self-contained

. In the *REGULATED* version it is the economic operator who declares other economic and financial information.

. In the *SELF-CONTAINED* version the contracting authority can specify the description of the economic or financial requirement; the minimum amount required and the currency; the period to which the amount relates to; a minimum rating and the rating schema. 

. In the *SELF-CONTAINED* the contracting authority can also specify the Lots to which the economic or financial requirement applies. This is not possible in the *REGULATED* version.

. The *SELF-CONTAINED* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, the only criterion defined is classified with the code:

	** CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENTS
	
