
=== VI.7 References on similar works, deliveries or services


==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Regulated and Self-contained

. For both versions, *REGULATED* and *SELF-CONTAINED* the contracting authority can require references for the type of project (or nature of the contract: works, supplies and services). 

. In the *REGULATED* version the economic operator supplies its references for one of those types of contract (software applications should take care of not including those types of contract that were not selected by the contracting authority).

. In the *REGULATED* version the economic operator provides a description for the reference, the amount of the contract, the period of execution and who where the recipients of its works, supplies or services.

. In the *SELF-CONTAINED* version the contracting authority can specify the minimum number of references required for the evaluation; an an unlimited number of free-text “requirements”, so the CA can provide requirements very specific to the procurement procedure. 

. In the *SELF-CONTAINED* the contracting authority can also specify the Lots to which each reference applies. From the references specified by the contracting authority, the economic operator can in turn specify to which Lots, amongst the ones it tenders to, the reference applies to. This is not possible in the *REGULATED* version.

. The *SELF-CONTAINED* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, there are three criteria with the same data structure (works, supplies and services references):

	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.WORKS_PERFORMANCE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SERVICES_DELIVERY_PERFORMANCE
