
=== VI.8 Abilities (I)


==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].

.Weighting 
[cols="<1,<4"]
|===
|*REQUIREMENT*|In an open procedure the CA has to consider all tenders that pass the selection criteria. The contract is awarded based on award criteria. 

For two stage procedures it should be possible to weight the "Technical and professional ability" (the rest of selection criteria should be always PASS/FAIL).

Weighting can be done either using percentage or points for one procedure. The CA should have a free text where they can describe the scoring methodology.
|===

==== Differences between Regulated and Self-contained

. In the *REGULATED* the contracting authority cannot specify any REQUIREMENT. It is the economic operator that provides descriptive information (free-text field) about the technicians or bodies.

. In the *SELF-CONTAINED* the contracting authority can provide a specific REQUIREMENT. For this example the CA expects the economic operator to provide information about the group of technicians that will supply support to the users. The CA can add and remove as many requirements as needed.

. In the *SELF-CONTAINED* the economic operator (EO) sees the REQUIREMENTs specified by the CA and can provide two groups of information (which are not disjoint):

** Group 1, information about one or more technicians: first and last name, profession, experience, additional information, how long the technician has worked for the EO, and online evidences.

** Group 2, information about the technical body to which all the technicians specified by the EO belong: name, area of experience, other information and online evidences.

. For procurement procedures organised in two stages the *SELF-CONTAINED* version allows the *weighting* of the technical and professional abilities.

. The *SELF-CONTAINED* is able to keep in the XML documents national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, the following eight criteria have the same data structure (all referred to the technical and professional abilities group):

	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.TECHNICIANS_FOR_QUALITY_CONTROL
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.TECHNICIANS_FOR_CARRYING_WORKS
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.FACILITIES_FOR_QUALITY_ENSURING
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.FACILITIES_FOR_STUDY_RESEARCH
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.SUPPLY_CHAIN_MANAGEMENT
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.PROFESSIONAL_QUALIFICATIONS
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.ENVIRONMENTAL_MANAGEMENT_MEASURES
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.EQUIPMENT