
=== VI.9 Abilities Checks (II)

==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Regulated and Self-contained

. In the *REGULATED* the contracting authority cannot specify REQUIREMENTs. The text of the Criterion is a QUESTION, retrieved from e-Certis, that needs to be answered with *Yes* or *No* by the economic operator.

. In the *SELF-CONTAINED* version the contracting authority can provide as many REQUIREMENTs as needed. These requirements are free-text fields that need to ask a 'binary' QUESTION. 

. In the *SELF-CONTAINED* the economic operator (EO) sees the REQUIREMENTs specified by the CA and, per each  REQUIREMENT the EO answers with *Yes* or *No*.

. The *SELF-CONTAINED* is able to keep in the XML documents national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, there is only one criterion with a particular (simple) data structure:

	**CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.CHECKS.ALLOWANCE_OF_CHECKS	