
=== VI.10 Abilities (III)

==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Regulated and Self-contained

. In the *REGULATED* version the contracting authority (CA) cannot specify REQUIREMENTs. The text of the Criterion asks the economic operator (EO) to provide a concrete number of groups of pairs 'Year + Number' of staff or manpower.

. In the *SELF-CONTAINED* version the contracting authority can provide the minimum number of pairs 'Year + Number' of staff or manpower expected, and a textual (descriptive) REQUIREMENT.

. In the *SELF-CONTAINED* version the economic operator can add or remove more pairs of 'Year + Number' of staff or manpower than the ones specified by the CA.

. The *SELF-CONTAINED* is able to keep in the XML documents national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, there are two criteria that share the same data structure:

	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.MANAGERIAL_STAFF
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT.AVERAGE_ANNUAL_MANPOWER