
==== XML Example (REGULATED and SELF-CONTAINED)

Notice that this XML example contains two representatives, as in the mock-up. 

.Economic operator's representatives
[source,xml]
----

<!-- Economic Operator Data -->

<cac:EconomicOperatorParty>
	<cac:QualifyingParty>
		<cbc:EmployeeQuantity>12167</cbc:EmployeeQuantity>
		<cac:FinancialCapability><cbc:ValueAmount currencyID="EUR">1203000000</cbc:ValueAmount></cac:FinancialCapability>
		<cac:Party>
			<!-- This EO company is NOT an SME -->
			<cbc:IndustryClassificationCode listID="EOIndustryClassificationCode" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">LARGE</cbc:IndustryClassificationCode>
			<!-- Notice that the ID and Name of the Pre-Qualification System is in the attributes. They would be captured from e-Certis. -->
			<cac:PartyIdentification>
				<cbc:ID schemeID="VAT" schemeAgencyID="ROLECE" schemeAgencyName="Registro Oficial de Licitadores y Empresas Clasificadas del Estado">B82387770</cbc:ID>
			</cac:PartyIdentification>
		</cac:Party>
	</cac:QualifyingParty>
	<cac:EconomicOperatorRole>
			<cbc:RoleCode listID="EORoleType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">SCLE</cbc:RoleCode>
			<cbc:RoleDescription>Sole entity or, in case of Consortium, Joint Venture or other types of groups, the leader of the group.</cbc:RoleDescription>
	</cac:EconomicOperatorRole>
	<cac:Party>
		<cbc:WebsiteURI>http://everis.com/global/en</cbc:WebsiteURI>
		<cac:PartyIdentification>
			<cbc:ID schemeAgencyID="VAT" schemeAgencyName="EU-COM-GROW" schemeID="VIES" schemeURI="http://ec.europa.eu/taxation_customs/vies/vieshome.do?locale=es" schemeName="VAT number">B82387770</cbc:ID>
		</cac:PartyIdentification>
		<cac:PartyName><cbc:Name>Everis, Spain, S.L.U.</cbc:Name></cac:PartyName>
		<cac:PostalAddress>
		<cbc:CityName>Madrid</cbc:CityName>
			<cbc:PostalZone>28050</cbc:PostalZone>
			<cac:AddressLine>
				<cbc:Line>Manoteras, 52</cbc:Line>
		</cac:AddressLine>
		<cac:Country>
			<cbc:IdentificationCode listID="CountryCodeIdentifier" listAgencyID="EU-COM-GROW" listVersionID="1.0">ES</cbc:IdentificationCode>
			<cbc:Name>Spain</cbc:Name>
		</cac:Country>
		</cac:PostalAddress>
		<cac:Contact>
			<cbc:Name>Xavi Ker; Ruth Gomis; Miguel Verde</cbc:Name>
			<cbc:Telephone>+34 91 749 00 00</cbc:Telephone>
			<cbc:ElectronicMail>Spain.Proposals.Office@everis.com</cbc:ElectronicMail>
		</cac:Contact>
		
		<!-- REPRESENTATIVES of the Economic Operator -->
		<!-- Representative 1 -->
		<cac:PowerOfAttorney>
		<cbc:Description>Total powers to make decisions on behalf of the company.</cbc:Description><--12-->
		<cbc:Description>Main legal representative with power to make decisions about any aspect related to public procurement contracts with public administrations.</cbc:Description><--7-->
		<cac:AgentParty>
			<cac:Person>
				<cbc:FirstName>Mary A.</cbc:FirstName><--1--> 
				<cbc:FamilyName>Smith</cbc:FamilyName><--8-->
				<cbc:BirthDate>1980-07-17</cbc:BirthDate><--2-->
				<!-- No element for "street and number" present. The user decided not to provide it --><--3-->
				<cbc:BirthplaceName>Brussels</cbc:BirthplaceName><--9-->
				<cac:Contact>
					<cbc:Telephone>+322124522</cbc:Telephone><--11-->
					<cbc:ElectronicMail>masmith@everis.com</cbc:ElectronicMail><--10-->
				</cac:Contact>
				<cac:ResidenceAddress>
					<cbc:CityName>Brussels</cbc:CityName><--5-->
					<cbc:PostalZone>1000</cbc:PostalZone><--4-->
					<cac:Country>
						<cbc:IdentificationCode listID="CountryCodeIdentifier" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">>BE</cbc:IdentificationCode><--6-->
						<cbc:Name languageID="en">Belgium</cbc:Name><--6-->
					</cac:Country>
				</cac:ResidenceAddress>					
			</cac:Person>
		</cac:AgentParty>
		</cac:PowerOfAttorney>
		<!-- Representative 2 -->
		<cac:PowerOfAttorney>
		<cbc:Description>Public Sector Responsible Manager</cbc:Description>
		<cbc:Description>Can sign contracts with the buyer on behalf of the Consortium.</cbc:Description>
		<cac:AgentParty>
			<cac:Person>
				<cbc:FirstName>Sergi</cbc:FirstName>
				<cbc:FamilyName>Mallol</cbc:FamilyName>
				<cbc:BirthDate>1960-06-21</cbc:BirthDate>
				<cbc:BirthplaceName>Barcelona</cbc:BirthplaceName>
				<cac:Contact>
					<cbc:Telephone>+34934947700</cbc:Telephone>
					<cbc:ElectronicMail>sergi.mallol@everis.com</cbc:ElectronicMail>
				</cac:Contact>
				<cac:ResidenceAddress>
					<cbc:CityName>Barcelona</cbc:CityName>
					<cbc:PostalZone>08020</cbc:PostalZone>
					<cac:Country>
						<cbc:IdentificationCode listID="CountryCodeIdentifier" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">>ES</cbc:IdentificationCode>
						<cbc:Name languageID="en">Spain</cbc:Name>
					</cac:Country>
				</cac:ResidenceAddress>					
			</cac:Person>
		</cac:AgentParty>
		</cac:PowerOfAttorney>
	</cac:Party>
</cac:EconomicOperatorParty>

<!-- Exclusion and selection Criteria, Responses and Evidences removed for the sake of brevity -->

----
<1> First Name of the natural person that represents the economic operator.
<2> Data of birth of the natural person that represents the economic operator.
<3> Notice that no street name and building number or postbox was provided. Hence the element `cac:AddressLine` has not been instantiated in this XML document.
<4> Postal or zip code in the city where the natural person lives.
<5> Name of the city where the natural person lives.
<6> Code representing the country where the natural person lives.
<7> Second line of the `cac:Description` element reserved to hold the additional information providing detailed information about the representation (such as the extent of the representation, its forms, purposes, etc.).  
<8> The family name of the natural person that represents the economic operator.
<9> Name of the place where the natural person representing the EO was born. This can be used to further identify the natural person.
<10> Electronic mail of the natural person.
<11> Telephone number of the natural person.
<12> Firts line of the `cac:Description` element reserved to hold the 'representation' role the natural person plays for this economic operator.




