
=== VIII.2. XML Example 1: Information about the EO

The information about the economic operator is distributed into the `cac:EconomicOperatorParty` element and 'data structures' that use the `cac:TenderingCriterion` element. The XML examples provided herein refer only to the data structured using the `cac:TenderingCriterion`. See chapter link:#vii-5-economic-operator[VII.5. Economic Operator] for more details and other XML examples.

==== XML snippet 1.a) EO registered in a PQS (criterion properties)

This XML shows the criterion properties to which the responses supplied by the economic operator are related. Some of these are *copied* from the QualificationApplicationRequest, other are added during the edition of the QualificationApplicationResponse (e.g. the ones necessary to ask for the data on the economic operator, such as name, date of birth, number of employees, etc.). See the answers corresponding to these criteria properties in the XML snippet 1.b) below.  

*Beware that* whilst the criterion properties may be from a *REGULATED* or *SELF-CONTAINED* ESPD, the `cac:TenderingCriterionResponse` (the answers) work always the same way regardless of whether the ESPD Response is *REGULATED* or *SELF-CONTAINED*. 

In this particular example, the snippet 1.a) contains criterion properties from a *SELF-CONTAINED* ESPD Response. 

.XML snippet 1.a) Data about an EO registered in a (pre)qualification system (SELF-CONTAINED)
[source,xml]
----
<!-- Economic Operator Data: properties -->

<!-- Criterion:EO registered in a PQS -->
	<cac:TenderingCriterion>
		<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9b19e869-6c89-4cc4-bd6c-ac9ca8602165</cbc:ID>
		<cbc:CriterionTypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">CRITERION.OTHER.EO_DATA.REGISTERED_IN_OFFICIAL_LIST</cbc:CriterionTypeCode>
		<cbc:Name>EO registered in a PQS</cbc:Name>
		<cbc:Description>If applicable, is the economic operator registered on an official list of approved economic operators or does it have an equivalent certificate (e.g. under a national (pre)qualification system)?</cbc:Description><--1-->
		<cac:TenderingCriterionPropertyGroup>
			<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">64162276-7014-408f-a9af-080426bfe1fd</cbc:ID>
			<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">ON*</cbc:PropertyGroupTypeCode>
			<cac:TenderingCriterionProperty>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7</cbc:ID>
				<cbc:Description>Your answer?</cbc:Description><--2-->
				<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
				<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">INDICATOR</cbc:ValueDataTypeCode>
			</cac:TenderingCriterionProperty>
			<cac:SubsidiaryTenderingCriterionPropertyGroup>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9026e403-3eb6-4705-a9e9-e21a1efc867d</cbc:ID>
				<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">ONTRUE</cbc:PropertyGroupTypeCode>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9f5528c1-6f7f-41e0-9287-054a0bef2f9f</cbc:ID>
					<cbc:Description>a) Alternative or additional name of the (pre)qualifiction system</cbc:Description><--3-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">DESCRIPTION</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">3eb9b248-21de-47fa-9aa2-e34d0bf1d32c</cbc:ID>
					<cbc:Description>c) Please state the references on which the registration or certification is based, and, where applicable, the classification obtained in the official list</cbc:Description><--4-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">DESCRIPTION</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">f6109977-1e25-4926-85f5-813db5c113d5</cbc:ID>
					<cbc:Description>d) Does the registration or certification cover all of the required selection criteria?</cbc:Description><--5-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">INDICATOR</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
			</cac:SubsidiaryTenderingCriterionPropertyGroup>
		</cac:TenderingCriterionPropertyGroup>
	</cac:TenderingCriterion>

<!-- Rest of elements removed for the sake of brevity -->
----
<1> Global QUESTION. If the answer to this QUESTION is *Yes* the content of the data structure must be processed.
<2> 'Your answer?' needed to decide how to handle the GUI, the validation or other processing. Expected answer data type: an INDICATOR (*true* or *false*). If the answer supplied is *true* the group of data in the data structure is processed. The response value shall be of type a `cbc:ResponseIndicator` (based on the CCT udt:IndicatorType, (see folder link:/.dist/mod/UBL-Entities-2.2-Pre-award.ods[mod] and  link:./dist/xsdrt/common/UBL-UnqualifiedDataTypes-2.2.xsd[/UBL-UnqualifiedDataTypes-2.2.xsd] to see examples of use and definition).
<3> 'Alternative name of the (pre)qualifiction system'. Expected answer data type: a DESCRIPTION -> the response value shall be a `cbc:Description` element.
<4> Reference or certifications that led to the classification of the EO in that PQS. Expected answer data type: a DESCRIPTION. -> the response value shall be a `cbc:Description` element.
<5> Scope of the certification regardin the selection criteria of this procurement procedure. Expected answer data type: an INDICATOR (*true* or *false*) -> the response value shall be a `cbc:ResponseIndicator` based on the CCT 'udt:IndicatorType' element.


==== XML snippet 1.b) EO registered in a PQS (answers)

Compare now the elements marked with circled numbers [2, 5] with the elements below marked with the same numbers.

.XML snippet 1.b) answers containing the information about the economic operator (REGULATED and SELF-CONTAINED)
[source,xml]
----

<!-- Economic Operator Data: answers -->

<!-- Answers to Criterion:EO registered in a PQS -->
	<!-- Property:Your answer? (PropertyID:343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7)--><--1-->
	<cac:TenderingCriterionResponse><--2-->
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">d9e19426-fc27-4c15-bdd3-a62a0de62a63</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">7eb59ae6-cc5e-472e-87d0-8fd0797ad325</cbc:ID>
			<cbc:ResponseIndicator>true</cbc:ResponseIndicator><--2-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<!-- Property:a) Alternative name of the (pre)qualifiction system (PropertyID:9f5528c1-6f7f-41e0-9287-054a0bef2f9f)--><--3-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">867cca96-d690-45b9-86db-f65a9ca613cd</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9f5528c1-6f7f-41e0-9287-054a0bef2f9f</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">8afda449-b2af-405c-a929-6108765a0bfc</cbc:ID>
			<cbc:Description>ROLECE, Registro Oficial de Licitadores y Empresas Clasificadas</cbc:Description> <--3-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<!-- Property:c) Please state the references on which the registration or certification is based, and, where applicable, the classification obtained in the official list (PropertyID:3eb9b248-21de-47fa-9aa2-e34d0bf1d32c)--> <--4-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">73e43330-424d-435f-8ba3-4b4d686e6144</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">3eb9b248-21de-47fa-9aa2-e34d0bf1d32c</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">32c90539-ef55-47b0-acf8-1fd80f90670d</cbc:ID>
			<cbc:Description>RF12134411-S, RF6113444124-S, RF-15552442-S, other</cbc:Description><--4-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	<!-- Property:d) Does the registration or certification cover all of the required selection criteria? (PropertyID:f6109977-1e25-4926-85f5-813db5c113d5)--><--5-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">6f3b6de0-7e01-49e2-ae11-75c804d0c88e</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">f6109977-1e25-4926-85f5-813db5c113d5</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">4df26770-c662-432b-be8b-a31b5b306eaa</cbc:ID>
			<cbc:ResponseIndicator>false</cbc:ResponseIndicator><--5-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>

<!-- Rest of elements removed for the sake of brevity -->

----
<1> Comment documenting to which criterion response this response is linked to.
<2> Response value to the global QUESTION. The data type is `cbc:ResponseIndicator`, which is consistent with the expected data value code INDICATOR (from the Code List link:./dist/cl/ods/ESPD-CodeLists-V02.00.00.xlsx[ResponseDataType]).
<3> Response value tot the 'Alternative name of the (pre)qualifiction system'. Expected answer data type was a DESCRIPTION -> the response value is a `cbc:Description` element.
<4> Reference or certifications. Expected answer data type was a DESCRIPTION. -> the response value is a `cbc:Description` element;
<5> Scope of the certification. Expected answer data type was an INDICATOR (*true* or *false*) -> the response value is a `cbc:ResponseIndicator`.

If you compare these two snippets with the mock-up you will notice that the field "b) Please provide the identification of the economic operator in the pre-qualification system" is not referred to or instantiated in the XML snippets above. This is because this identification of the economic party is placed in the element `cac:EconomicParty/cac:QualifyingParty/cac:Identification/cbc:ID`. See the XML example in section "link:l#xml-example-self-contained-economic-operator[XML Example (SELF-CONTAINED economic operator)]" and look for this fragment of XML code (circle #19 in the mock-up):

.Identification of the EO in the PQS
[source,xml]
----
<cac:PartyIdentification>
		<cbc:ID schemeID="VAT" schemeAgencyID="ROLECE" schemeAgencyName="Registro Oficial de Licitadores y Empresas Clasificadas del Estado">B82387770</cbc:ID>
</cac:PartyIdentification>
----

==== XML snippet 2.a) Lots the EO tenders to (criterion properties)

If the procurement procedure is divided into Lots the ESPD Request will have multiple instances of the element `cac:ProcurementProjectLot` (see section "link:#iii-10-lots-self-contained-espd[III.10 Lots - Self-contained ESPD]"). 

Based on the identifiers of the Lots specified in the ESPD Request, software applications can require the economic operator to link its answers to the Lots. One example of this are when the EO specifies the Lots it tenders to; (another example is when the EO links its references to works, supplies or services similar to the procurement procedure it is tendering. In the *SELF-CONTAINED* ESPD a group of references can be linked to one or more Lots. See the "XML Example 2" below). 


.Lots the EO tenders to
[source,xml]
----
<!-- Criterion:Lots the EO tenders to -->
<cac:TenderingCriterion>
	<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">8b9700b7-b13c-41e6-a220-6bbf8d5fab31</cbc:ID>
	<cbc:CriterionTypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">CRITERION.OTHER.EO_DATA.LOTS_TENDERED</cbc:CriterionTypeCode>
	<cbc:Name>Lots the EO tenders to</cbc:Name>
	<cbc:Description>Lots selected by the economic operator</cbc:Description><--1-->
	<cac:TenderingCriterionPropertyGroup>
		<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">289f39b3-2a15-421a-8050-a29858031f35</cbc:ID>
		<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">ON*</cbc:PropertyGroupTypeCode>
		<!-- This property below provides the UUID to which all the Lot IDs provided by the EO in the response will be linked, thus constructing the List -->
		<cac:TenderingCriterionProperty><--2-->
			<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">ca0e6adb-a8a3-40f0-9ffa-f9f0b3d95e31</cbc:ID>
			<cbc:Description>Lot IDs</cbc:Description>
			<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
			<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">IDENTIFIER</cbc:ValueDataTypeCode><--3-->
		</cac:TenderingCriterionProperty>
	</cac:TenderingCriterionPropertyGroup>
</cac:TenderingCriterion>
----
<1> Text description the QUESTION.
<2> Property to which all the Lots provided by the EO will be linked to.
<3> The expected type of data is an IDENTIFIER. This implies that in the response the response value shall be an element based on the `cbc:Identifier` type defined by UBL; see snippet 2.b) below.

Compare the circled numbers in the XML snippet above with the circled numbers in the XML snippet below.

==== XML snippet 2.b) Lots the EO tenders to (answers)

.Lots the EO tenders to
[source,xml]
----
<!-- Answer to Criterion:Lots the EO tenders to -->
<!-- Property:Lot IDs (PropertyID:ca0e6adb-a8a3-40f0-9ffa-f9f0b3d95e31) --><--1-->
<cac:TenderingCriterionResponse>
	<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9bbe78e9-e342-46fa-974c-299dc87087ef</cbc:ID>
	<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">ca0e6adb-a8a3-40f0-9ffa-f9f0b3d95e31</cbc:ValidatedCriterionPropertyID><--2-->
	<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
	<cac:ResponseValue> <--3-->
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">ea861f62-50c8-4f57-9212-ffbb6f2a10a8</cbc:ID>
		<cbc:ResponseID>Lot4</cbc:ResponseID><--4-->
	</cac:ResponseValue>
	<cac:ResponseValue>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">bcde4e84-936d-4b27-a873-3fe74860b0a7</cbc:ID>
		<cbc:ResponseID>Lot5</cbc:ResponseID><--5-->
	</cac:ResponseValue>
</cac:TenderingCriterionResponse>

----
<1> Comments identifying the criterion.
<2> The UUID of the criterion property thus linking this answer to it and all its content, in this case a *list* of 2 values.
<3> First value of the list (compare to the value supplied by the EO, circle #27 in the mock-up).
<4> Notice that the value is placed in a `cbc:Identifier` (CCT `udt:IdentifierType`) qualified as `ResponseID` (see folder link:/.dist/mod/UBL-Entities-2.2-Pre-award.ods[mod] and  link:./dist/xsdrt/common/UBL-UnqualifiedDataTypes-2.2.xsd[/UBL-UnqualifiedDataTypes-2.2.xsd] to see examples of use and definition). This is consistent with the fact that the criterion property (see XML snippet 2.a) specifies the value *IDENTIFIER* in the element `cac:ValueDataTypeCode`.  
<5> Second value of the list (compare to the value supplied by the EO, circle #27 in the mock-up).

