
==== Request/Response XML Example

To start with a simple example let us re-take the last case presented in section link:#vii-1-reduction-of-candidates[Reduction of candidates].

The first thing to take into account is that the responses go at the end of the document, just after the last set of
REQUIREMENT(s) and QUESTION(s) that were *copied* from the ESPD-Request into the ESPD-Response, and before the evidences.

The second important thing is to keep in mind is that each response is linked to one, and only one, QUESTION via the
identifier of that QUESTION.

Having said this, imagine that the following snippet of XML code is the last criterion from the ESPD-Request that has
been instantiated in your ESPD-Response (pay attention to the bullets and comments under the example).

.Reduction of Candidates - (QUESTION(s) in the ESPD-Request)
[source,xml]
----
<!-- ... beginning of document removed for brevity -->

<cac:TenderingCriterion>
    <cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">51c39ba9-0444-4967-afe9-36f753b30175</cbc:ID>
    <cbc:CriterionTypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">CRITERION.OTHER.EO_DATA.REDUCTION_OF_CANDIDATES</cbc:CriterionTypeCode>
    <cbc:Name>Reduction of the number of qualified candidates</cbc:Name>
    <cbc:Description>The economic operator declares that It meets the objective and non discriminatory criteria or rules to be applied in order to limit the number of candidates in the following way:</cbc:Description>
    <cac:TenderingCriterionPropertyGroup>
        <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">ecc69670-f428-4446-908f-689568ca0d0d</cbc:ID>
        <cbc:PropertyGroupTypeCode listID="PropertyGroupType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">ON*</cbc:PropertyGroupTypeCode>
        <cac:TenderingCriterionProperty> <--1-->
            <cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">c110177c-aa9a-4acd-809a-79a2353a41ef</cbc:ID>
            <cbc:Description>Your answer?</cbc:Description> <--2-->
            <cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">QUESTION</cbc:TypeCode><--3-->
            <cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">INDICATOR</cbc:ValueDataTypeCode><--4-->
        </cac:TenderingCriterionProperty>
        <cac:SubsidiaryTenderingCriterionPropertyGroup><--5-->
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">f13754df-7e15-4155-aaa6-7ca6407baa47</cbc:ID>
            <cbc:PropertyGroupTypeCode listID="PropertyGroupType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">ONTRUE</cbc:PropertyGroupTypeCode><--6-->
            <cac:TenderingCriterionProperty><--7-->
                <cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">e437cac1-3a89-4f36-bcc7-3219dda49d30</cbc:ID>
                <cbc:Description>Please describe them</cbc:Description><--8-->
                <cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">QUESTION</cbc:TypeCode>
                <cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">DESCRIPTION</cbc:ValueDataTypeCode><--8-->
            </cac:TenderingCriterionProperty>
        </cac:SubsidiaryTenderingCriterionPropertyGroup>
    </cac:TenderingCriterionPropertyGroup>
    <cac:TenderingCriterionPropertyGroup>
        <!-- Block requesting evidences: removed for the sake of brevity and clarity -->
    </cac:TenderingCriterionPropertyGroup>
</cac:TenderingCriterion>

<!-- ... rest of document removed for brevity -->
----
<1> Here starts the first QUESTION (a criterion property of type QUESTION, the type follows below).
<2> Here the contracting authority (CA) is requesting to the economic Operator that it states whether it meets the ''objective and non-discriminatory criteria or rules [..]".
<3> The type of the criterion property: QUESTION.
<4> The type of data that the economic operator (EO) will have to provide in the response (`true` or `false)`.
<5> The next QUESTION is enclose in a SUBGROUP because the processing instruction `ONTRUE` can be used only by GROUPs or SUBGROUPs of REQUIREMENTs and QUESTIONs.
<6> If the previous QUESTION is answered with a `true` the EO will be presented with a new demand expressed in th next QUESTION.
<7> The QUESTION ''Please describe them'', presented if the EO answered `true` to the previous QUESTION (''Your answer''). <8> The type of data expected here is a free text bythe EO (for the Response, a DESCRIPTION maps to the UBL-2.2 element cbc:Description, which is an extension of the xsd:String).


==== XML example (Responses to the QUESTION(s))

This other XML snippet below shows the responses to the two QUESTION(s) expressed in the ESPD-Request for this criterion (the
block related to evidences is omitted for the sake of clarity and brevity):

.Reduction of Candidates - (answers in the ESPD-Response)
[source,xml]
----
<!-- ... beginning of document removed for brevity -->

<cac:TenderingCriterionResponse>
    <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">d47daca4-4a27-4461-9db9-f483d3b7a114</cbc:ID>
    <cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">c110177c-aa9a-4acd-809a-79a2353a41ef</cbc:ValidatedCriterionPropertyID> <--1-->
    <cac:ResponseValue>
            <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">de6f1bdd-abce-42f7-b9b8-30c4e7c4c94d</cbc:ID>
            <cbc:ResponseIndicator>true</cbc:ResponseIndicator> <--2-->
    </cac:ResponseValue>
</cac:TenderingCriterionResponse>
<cac:TenderingCriterionResponse>
    <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">d47daca4-4a27-4461-9db9-f483d3b7a114</cbc:ID>
    <cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">e437cac1-3a89-4f36-bcc7-3219dda49d30</cbc:ValidatedCriterionPropertyID><--3-->
    <cac:ResponseValue>
            <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.1.0">de6f1bdd-abce-42f7-b9b8-30c4e7c4c94d</cbc:ID>
            <cbc:Description>This Consortium fulfills all the conditions defined by the buyer in the contract notice, and notably
             the Consortium is duly registered in the national pre-qualification system of the country of the Consortium lead where
             all the information about its classification and documentation about its financial standing are up to the date.</cbc:Description><--4-->
    </cac:ResponseValue><--3-->
</cac:TenderingCriterionResponse>

<!-- ... rest of document removed for brevity -->
----
<1> Notice this UUID is identical to the `cac:TenderingCriterionProperty` one. This is the way the UBL-2.2 Qualification Application Response document links each QUESTION(s) to one response (and only one), or viceversa.
<2> The economic operator states here that it meets the criteria. Notice that the data element is the UBL-2.2 element `cbc:ResponseIndicator`, which is an
''semantisation'' (a specialisation) of cbc:Indicator and therefore corresponds to the type of data expected by the CA in the Request (in `cbc:ValueDataTypeCode`).
<3> This is the UUID corresponding to the QUESTION in the Request ''Please describe them''.
<4> The economic operator describes how it meets the criteria. The data element containing the explanation by the EO. Notice that the type of data is the UBL-2.2 element `cbc:Description`, as requested by the CA in `cbc:ValueDataTypeCode`.