
==== XML Example 1: Information about the EO

The information about the economic operator is distributed into the `cac:EconomicOperatorParty` element and 'data structures' that use the `cac:TenderingCriterion` element. The XML examples provided herein refer only to the data structured using the `cac:TenderingCriterion`. See chapter link:#vii-5-economic-operator[VII.5. Economic Operator] for more details and other XML examples.

===== XML snippet 1.a) Criterion Properties

This XML shows the criterion properties to which the responses supplied by the economic operator are related. Some of these are *copied* from the QualificationApplicationRequest, other are added during the edition of the QualificationApplicationResponse (e.g. the ones necessary to ask for the data on the economic operator, such as name, date of birth, number of employees, etc.). See the answers corresponding to these criteria properties in the XML snippet 1.b) below.  

*Beware that* whilst the criterion properties may be from a *REGULATED* or *SELF-CONTAINED* ESPD, the `cac:TenderingCriterionResponse` (the answers) work always the same way regardless of whether the ESPD Response is *REGULATED* or *SELF-CONTAINED*. 

In this particular example, the snippet 1.a) contains criterion properties from a *SELF-CONTAINED* ESPD Response. 

.XML snippet 1.a) Data about an EO registered in a (pre)qualification system (SELF-CONTAINED)
[source,xml]
----
<!-- Economic Operator Data: properties -->

<!-- Criterion:EO registered in a PQS -->
	<cac:TenderingCriterion>
		<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9b19e869-6c89-4cc4-bd6c-ac9ca8602165</cbc:ID>
		<cbc:CriterionTypeCode listID="CriteriaTypeCode" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">CRITERION.OTHER.EO_DATA.REGISTERED_IN_OFFICIAL_LIST</cbc:CriterionTypeCode>
		<cbc:Name>EO registered in a PQS</cbc:Name>
		<cbc:Description>If applicable, is the economic operator registered on an official list of approved economic operators or does it have an equivalent certificate (e.g. under a national (pre)qualification system)?</cbc:Description><--1-->
		<cac:TenderingCriterionPropertyGroup>
			<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">64162276-7014-408f-a9af-080426bfe1fd</cbc:ID>
			<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">ON*</cbc:PropertyGroupTypeCode>
			<cac:TenderingCriterionProperty>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7</cbc:ID>
				<cbc:Description>Your answer?</cbc:Description><--2-->
				<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
				<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">INDICATOR</cbc:ValueDataTypeCode>
			</cac:TenderingCriterionProperty>
			<cac:SubsidiaryTenderingCriterionPropertyGroup>
				<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9026e403-3eb6-4705-a9e9-e21a1efc867d</cbc:ID>
				<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">ONTRUE</cbc:PropertyGroupTypeCode>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9f5528c1-6f7f-41e0-9287-054a0bef2f9f</cbc:ID>
					<cbc:Description>a) Alternative or additional name of the (pre)qualifiction system</cbc:Description><--3-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">DESCRIPTION</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">3eb9b248-21de-47fa-9aa2-e34d0bf1d32c</cbc:ID>
					<cbc:Description>c) Please state the references on which the registration or certification is based, and, where applicable, the classification obtained in the official list</cbc:Description><--4-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">DESCRIPTION</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
				<cac:TenderingCriterionProperty>
					<cbc:ID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">f6109977-1e25-4926-85f5-813db5c113d5</cbc:ID>
					<cbc:Description>d) Does the registration or certification cover all of the required selection criteria?</cbc:Description><--5-->
					<cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">QUESTION</cbc:TypeCode>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="02.00.00">INDICATOR</cbc:ValueDataTypeCode>
				</cac:TenderingCriterionProperty>
			</cac:SubsidiaryTenderingCriterionPropertyGroup>
		</cac:TenderingCriterionPropertyGroup>
	</cac:TenderingCriterion>

<!-- Rest of elements removed for the sake of brevity -->
----
<1> Global QUESTION. If the answer to this QUESTION is *Yes* the content of the data structure must be processed.
<2> Expected answer data type: an INDICATOR (*true* or *false*).
<3> Expected answer data type: a DESCRIPTION.
<4> Expected answer data type: a DESCRIPTION.
<5> Expected answer data type: an INDICATOR (*true* or *false*).

Compare now the elements marked with circled numbers [2, 5] with the elements below marked with the same numbers.

.XML snippet 1.b) answers containing the information about the economic operator (REGULATED and SELF-CONTAINED)
[source,xml]
----

<!-- Economic Operator Data: answers -->

<!-- Answers to Criterion:EO registered in a PQS -->
	<!-- Property:Your answer? (PropertyID:343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7)--><--2-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">d9e19426-fc27-4c15-bdd3-a62a0de62a63</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">343b5c92-2a5f-4ef7-9d8a-41c8e7b70aa7</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">7eb59ae6-cc5e-472e-87d0-8fd0797ad325</cbc:ID>
			<cbc:ResponseIndicator>true</cbc:ResponseIndicator><--2-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<!-- Property:a) Alternative or additional name of the (pre)qualifiction system (PropertyID:9f5528c1-6f7f-41e0-9287-054a0bef2f9f)--><--3-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">867cca96-d690-45b9-86db-f65a9ca613cd</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">9f5528c1-6f7f-41e0-9287-054a0bef2f9f</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">8afda449-b2af-405c-a929-6108765a0bfc</cbc:ID>
			<cbc:Description>ROLECE, Registro Oficial de Licitadores y Empresas Clasificadas</cbc:Description> <--3-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<!-- Property:c) Please state the references on which the registration or certification is based, and, where applicable, the classification obtained in the official list (PropertyID:3eb9b248-21de-47fa-9aa2-e34d0bf1d32c)--> <--4-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">73e43330-424d-435f-8ba3-4b4d686e6144</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">3eb9b248-21de-47fa-9aa2-e34d0bf1d32c</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">32c90539-ef55-47b0-acf8-1fd80f90670d</cbc:ID>
			<cbc:Description>RF12134411-S, RF6113444124-S, RF-15552442-S, other</cbc:Description><--4-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	<!-- Property:d) Does the registration or certification cover all of the required selection criteria? (PropertyID:f6109977-1e25-4926-85f5-813db5c113d5)--><--5-->
	<cac:TenderingCriterionResponse>
		<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">6f3b6de0-7e01-49e2-ae11-75c804d0c88e</cbc:ID>
		<cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">f6109977-1e25-4926-85f5-813db5c113d5</cbc:ValidatedCriterionPropertyID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="02.00.00"/>
		<cac:ResponseValue>
			<cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="02.00.00">4df26770-c662-432b-be8b-a31b5b306eaa</cbc:ID>
			<cbc:ResponseIndicator>false</cbc:ResponseIndicator><--5-->
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>

<!-- Rest of elements removed for the sake of brevity -->

----
If you compare these two snippets with the mock-up you will notice that the field "b) Please provide the identification of the economic operator in the pre-qualification system" is not referred to or instantiated in the XML snippets above. This is because this identification of the economic party is placed in the element `cac:EconomicParty/cac:QualifyingParty/cac:Identification/cbc:ID`. See the XML example in section "link:l#xml-example-self-contained-economic-operator[XML Example (SELF-CONTAINED economic operator)]" and look for this fragment of XML code (circle #19):

.Identification of the EO in the PQS
[source,xml]
----
<cac:PartyIdentification>
		<cbc:ID schemeID="VAT" schemeAgencyID="ROLECE" schemeAgencyName="Registro Oficial de Licitadores y Empresas Clasificadas del Estado">B82387770</cbc:ID>
</cac:PartyIdentification>
----

