=== 1.3 UBL-2.3 Documents and libraries

UBL-2.3 defines thousands of different information components and dozens of documents. This guide describes and illustrates only those elements from UBL-2.3 that are actually used by the eESPD. Thus the ESPD-EDM reuses only a small set of those components and only 2 documents: *QualificationApplicationRequest* (for the ESPD Request) and *QualificationApplicationResponse* (for the ESPD Response).

UBL-2.3 distributes two sets of XSD schemas: see folders xsd and xsdrt of the UBL distribution package. The xsd folder contains the schemata fully documented (with dictionary entry names, definitions, examples, etc.); whilst the xsdrt schemata are not likewise documented and are frequently used in production environments (*rt* stands for “run-time”).

The previous ESPD-EDM versions used its own libraries where Criterion and Evidence-related aggregate and components were defined (components prefixed with cac-ccv:, cac-cev, cbc-ccv and cbc-cev).

This new version uses components exclusively defined by UBL-2.3 in two main libraries: Common Aggregate Components (file UBL-CommonAggregateComponents-2.3.xsd.xsd) and Common Basic Components (UBL-CommonBasicComponents-2.3.xsd.xsd).

The usual prefix used to identify Common Aggregate Components is cac:. The prefix for Common Basic Components is cbc:.

All the materials developed by UBL-2.3 Technical Committee can be accessed here: link:https://github.com/oasis-tcs/ubl-2.3-artefacts[here].

