ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Scope of this document

==== Contracts above the threshold and below the threshold

The Directive (namely Article 4) regulates in detail those  public procurement procedures which values of contract exceed certain amounts. These amounts, also known as 
''thresholds'', vary depending on the type of the contract and of the administration level of the contracting authority.

Those contracts that fall under this article 4 of the Directive are called contracts ''above the threshold'', and the rest are known as contracts ''below the threshold''.footnote:[Examples of contracts above the threshold would be: (a) public works contracts which value is above EUR 5 186 000; (b) public supply and service contracts which value is above EUR 134 000 awarded by central government authorities; (c) public supply and service contracts which value is above EUR 207 000 awarded by sub-central contracting authorities; (d) EUR 750 000 for public service contracts for social and other specific services listed in Annex XIV. For more details, see Article 4 (where the threshold are established), Article 5 (about special cases associated to Lots), and Annexes III and XIV of the Directive 2014/24/EU. ].

The ESPD-EDM is rich and flexible enough so as to allow ESPD instances for contracts above and below the threshold. However this document is oriented exclusively to illustrate 
how to create ESPD electronic documents for contracts above the threshold.

==== In-Scope

. This document provides commented examples only on ESPD relating to contracts above the threshold
. The explanations, examples, rules, recommendations, etc. only apply to the XML documents that intend to be compatible with the import and export features of the ESPD Service

==== Out-of-Scope

Many of the requirements and recommendations expressed in this document MAY NOT be valid for contracts below the threshold. However, from a purely technical point of view, the examples commented MAY be used to understand how the ESPD-EDM works and to create, in a normalized way, XML instances containing criteria for contracts below the threshold.
