ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Additional Document Reference

The ESPD EDM reuses this UBL-2.1 component to allow both the contracting body (in the ESPDRequest) and the economic operator (in the ESPDResponse)
to include references to documents that they might consider relevant including in the XML instances of both types of documents.

The class used for this, `cac:AdditionalDocumentReference` ''is a'' `cac:DocumentReference` class defined in the UBL-2.1
Common Aggregate Components library (see the folder _xsd/common/UBL-CommonAggregateComponents-2.1.xsd_ file of the 
http://docs.oasis-open.org/ubl/UBL-2.1.html[UBL-2.1 specification])

Although this class has a rich data structure the ESPD Service at most expects the following data from it:

	* The document ID;
	* The issue date and time;
	* The document type code;
	* A title for the document; and
	* A description of its content and/or intended purpose; and 
	* The URL where to access its content.
	
This example below illustrates how these fields from the cac:AdditionalDocumentReference are used in the ESPDRequest XML document. Beware that
this is a special case (see General rule 1, below), as it refers to the Contract Notice published in the Publications Office's 
http://ted.europa.eu/TED/main/HomePage.do[TeD] Service:

[source,xml]
.Use of the class cac:AdditionalDocumentReference to specify the CN in TeD
----
 <cac:AdditionalDocumentReference>
      <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeAgencyName="DG GROW (European Commission)" schemeVersionID="1.1">2015/S 252-461137</cbc:ID><!--1-->
      <cbc:DocumentTypeCode listID="ReferencesTypeCodes" listAgencyID="EU-COM-GROW" listVersionID="1.0">TED_CN</cbc:DocumentTypeCode><!--2-->
      <cac:Attachment>
         <cac:ExternalReference>
            <cbc:FileName>Belgium-Brussels: European Resource Efficiency Excellence Centre</cbc:FileName><!--3-->
            <cbc:Description>The objective of this contract is to set up a virtual European Resource Efficiency Excellence Centre. The Centre will provide information and support to European SMEs, business intermediaries, resource efficiencypractitioners and other interested parties such as regional authorities.</cbc:Description><!--4-->
         </cac:ExternalReference>
      </cac:Attachment>
   </cac:AdditionalDocumentReference>
----
<1> Unique ID for this document (the TeD Contract Notice reference number)
<2> The COM's code for this type of content
<3> A title for the document
<4> A description of the content and intended use of this document
	
[NOTE]
====
* The ID of this type of document has a special pattern [][][][]/S [][][]-[][][][][][]. This pattern is the ID scheme defined by *TeD*
* The title for the document is placed in the _cbc:FileName_ field
====
  