ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Conflict of interest

The category ''Conflicts of Interest'' encompasses different exclusion criteria which are 
more heterogeneous than the ones described until now. Three different data structures are 
used in the ESPD Service to describe different conflict of interest criteria:

	* CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION: Conflict of interest due 
	to ''early termination, damages or other comparable sanctions'';
	* CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PREPARATION: Conflict of interest 
	due to ''direct or indirect involvement in the preparation of this procurement procedure'';
	* CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PARTICIPATION: Conflict of interest due 
	to ''participation in the procurement procedure''; and
	* CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION: Conflict of interest due 
	for being ''guilty of misinterpretation, withheld information, able to provide required 
	documents and obtained confidential information of this procedure''.

The following subsections show the data structures and examples for these three groups of 
criteria related to conflict of interests: