ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Technical and professional abilities

Many criteria under the group of technical and professional abilities share one simple structure where only a description and 
additional information available online are requested. 

That is mainly the case for the category:

	* CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.* grouping the following criteria: ''Supply chain management'', ''Tools, plant or technical equipment'', ''Environmental management measures''; ''Technicians or technical bodies for quality control'', ''For works contracts: technicians or technical bodies to carry out the work'', Technical facilities and measures for ensuring quality'', ''Study and research facilities'' and ''Educational and professional qualifications'';
	* CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.* also has a specific (iterative) structure where several groups of requirements specific for reference to experience are requested: ''For works contracts: performance of works of the specified type'', ''For supply contracts: performance of deliveries of the specified type'', ''For service contracts: performance of services of the specified type'';
	* CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL. CHECKS. ALLOWANCE_OF_CHECKS: represents the criterion ''Allowance of checks'' which has however a special data structure of its own (a response ''yes'' or ''no'' is simply expected;
	* CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.MANAGEMENT: ''Number of managerial staff'', and ''Average annual manpower''. And two other sub-elements with different structures:
		** ARTEFACTS: ''For supply contracts: samples, descriptions or photographs without certification of authenticity'' and For supply contracts: samples, descriptions or photographs with certification of authenticity '' '';
		** SUBCONTRACTING_PROPORTION: the criterion ''Subcontracting proportion'' has its own very simple structure in the ESPD Service currently requesting for a text;
	* CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES:
		** QUALITY_ASSURANCE: ''For supply contracts: certificates by quality control institutes'' and ''Certificates by independent bodies about quality assurance standards'';
		** ENVIRONMENTAL_MANAGEMENT: ''Certificates by independent bodies about environmental management systems or standards''.