[.text-left]
=== I.1 Objectives and scope

==== I.1.1 The Directive
Article 59 of the new Public Procurement Directive 2014/24/EC (henceforth 'the Directive') introduced a new concept, the *European Single Procurement Document* (ESPD) which is a self-declaration document intended for preliminary evidence in a public procurement procedure. By mapping out equivalent certificates between MS, the ESPD replaces certificates issued by public authorities or a third party involved in a procedure. It is thus a valuable facilitator for cross-border participation 
of a greater number of potential operators in public procurement procedures and a valuable tool for integrating the European Single Market.

The European Commission (EC) has developed a data model and 'semantic assets' for the exchange of the ESPD between any Procurement stakeholder’s system. This document illustrates in detail how to use the model and assets in compliance with the Directive.

The model, named ESPD-EDM (standing for European Single Procurement Document - Exchange Data Model) defines two electronic (XML) documents:

The *ESPD Request*, a document providing information about the contracting authority, the procurement procedure and the exclusion and selection criteria established for the procurement procedure.

The *ESPD Response*, the document that is filled-in by the Economic Operators stating whether they fulfill or not the criteria required in the ESPDRequest, and providing the sources where evidences can be obtained to prove that the criteria are met.

This guide is intended to facilitate the understanding of the model underlying the implementation of the ESPD Request and ESPD Response XML documents. With that objective in mind the reader is provided with examples and rules relating to how the content of ESPD XML document should look like and be processed.

The content of the guide is mainly addressed to the development teams from the Member States, economic operators, information providers or any other party interested in understanding how the ESPD Exchange Data Model works and how to use it to produce XML instances of ESPD Request and ESPD Response documents.

[.text-left]
==== I.1.2 Contracts above the threshold and below the threshold
The Directive (namely Article 4) regulates in detail those public procurement procedures which values of contract exceed certain amounts. These amounts, also known as 'thresholds', vary depending on the type of the contract and of the administration level of the contracting authority.

Those contracts that fall under this article 4 of the Directive are called contracts 'above the threshold', and the rest are known as contracts 'below the threshold'.

The ESPD-EDM is rich and flexible enough so as to allow ESPD instances for contracts above and below the threshold. However this document is oriented exclusively to illustrate how to create ESPD electronic documents for contracts above the threshold.
