
=== IV.5 Mock-ups

Chapters link:#v-exclusion-criteria[V. Exclusion Criteria] and link:#vi-selection-criteria[VI. Selection Criteria]
describe in detail the different *types* of exclusion and selection criteria defined and used in the ESPD-EDM.
By *type* of criterion we refer to criteria that share common characteristics, namely how they are structured.
Each type of criterion is presented from three perspectives:

. *Layout and functional*: Mock-ups are provided to explain which data are expected and, to some extent, how software applications should behave (what to show/hide, validate or process depending on variables like 'what the user answers' or 'which is the role of the user'). Mock-ups are provided for both the contracting authority and economic operator perspectives; 

. *Structural*: two spread-sheet books (two files) are provided with this document aimed to explain how each type of criterion is organised (each book contains different sheets (tabs). Each 'tab' shows the structure of one type of criterion (e.g. 'EG-Convictions', 'EG-Contributions', ..., 'SC-Suitability', 'SC_References', etc.; where 'EG' stands for 'Exclusion Grounds', and 'SC' stands for 'Selection Criteria').    

** ESPD-CriteriaTaxonomy-REGULATED-V2.1.0.xlsx, where the structures of the REGULATED ESPD criteria are defined;

** ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx, where the structures of the SELF-CONTAINE ESPD criteria are defined;

. *XML Implementation*: 

Each mock-up (or pair of CA + EO mock-ups) represent the structure represented in the data structure spread-sheet and in the supplied XML example. Whilst the mock-up and XML example are quite self-explanatory, to understand the value of the data structure spread-sheet needs to be explained; which is the mission of this very next sub-section below.

