== Release Notes

=== v3.0.0 (January 2021)

The ESPD-EDM version 3.0.0 focuses on its evolution for the alignment with eForms to ensure the maximum interoperability between models. It also includes fixed errors and changes suggested by the Member States and other Stakeholders within the Github repositories (issues workspace).  
The list below details the different changes included in the current release 3.0.0 of the ESPD-EDM: 


==== Online documentation

The following changes have been introduced: 
* Online documentation has been split between business and technical documentation in order to ensure a better understanding of the ESPD by targeting each area. *_‘Business Handbook’_* and *_‘Technical Handbook’_* are now available.

* *_‘Business Handbook’_* is focused on providing business domain information for the ESPD-EDM, helping non-technical profiles to better understand the rationale to use the ESPD and its context. 

* *_‘Technical Handbook’_* includes information related to the implementation of the ESPD and how it works technically. The technical part of the previous “ESPD Implementation Guide” has been updated with the required changes due to the evolution of the model. 
It also must be taken into account that the current version of the ESPD-EDM is using a single model, the former EXTENDED model. Therefore, all information related to the BASIC model has been removed, and information related to the EXTENDED model has been updated according to the improvements included in the last version of the ESPD-EDM. 


==== TOOP Requirements in ESPD-EDM (UBL2.2) Schema

A mapping for TOOP requirements to UBL2.3 Schema (which is the one used by ESPD-EDM v3.0.0) has been made, and it has been proved that they are fully mappable. For more information, please refer to the dedicated section of the online documentation.
You can also access issue link:https://github.com/ESPD/ESPD-EDM/issues/277[#277], where the topic was discussed.


==== Code Lists

Taking into account the need for alignment with eForms, the different code lists used by the ESPD-EDM have been updated and adapted accordingly. The maintenance of these code lists will fall under the Publications Office in most of the cases. 
EU Vocabularies used also by eForms have been adopted when needed, for example in the cases of country, economic-operator-size, currency, language, etc.
Other code lists have been removed since the information will be provided by eForms and, therefore, users will not need to provide this information into ESPD. Instead, the information shall be gathered from eForms’ notices and placed, when needed, into the proper placeholder. This is the case of the following code lists, which have been removed from ESPD:

* BidType
* ProcedureType
* ProjectType
* ServicesProjectSubType
* LegislationType
* EvaluationMethodType (version 3.0.0 of the ESPD does not include weights, in order to keep the model as simple as possible)
* CPVCodes 

A new code list has been added related to the requirement of being enrolled in a professional register (criterion #25 Suitability I ‘Abilities’ – “prof-regist”): 

* Occupation

It is worth to note that this code list is based on link:https://ec.europa.eu/esco/portal/occupation[ESCO]. In the future, the ESCO API will be used to retrieve ESCO codes.

==== ESPD Criteria Data Structures (Former ESPD Criteria Taxonomy)

The first change applied to the former Criteria Taxonomy is that from version 3.0.0 and on it will be named ESPD Criterion. 
As already explained, version 3.0.0 of the ESPD-EDM does not distinguish between EXTENDED or BASIC. Therefore, there is only a single document for the definition of criteria data structures. 

Codes have been modified in order to make them business agnostic and allow their reuse across sectors (see ‘criterion’ tab within ESPD-CodeLists-V.3.0.0). Also, codes per all criteria have been adapted accordingly (see column ‘ElementType’).

The following criteria have been removed from the file *_ESPD-Criterion-V.3.0.0_*: 

* CRITERION.OTHER.CA_DATA.LOTS_SUBMISSION
* Criteria DEFENCE-SELECTION-OTHER and UTILITIES-SELECTION-OTHER
* CRITERION.OTHER.EO_DATA.LOTS_TENDERED

A QUESTION_SUBGROUP has been added to selection criteria to know if the tendering EO is going to fill in the criteria by itself or will rely on other entities to do so (additional information than the _eo-group_ criterion). 

==== UUIDs

New UUIDs have been added for the newly created Criteria, groups and sub-groups where needed. For a comprehensive list of the new UUIDs and their creation reason, please refer to the following link:https://github.com/ESPD/ESPD-EDM/tree/3.0.0/docs/src/main/asciidoc/assets[document].  

==== Business Rules

The ESPD 3.0.0 includes changes in the business rules used to validate the ESPD requests and responses: 

* ‘Context’ element has been removed since it was referring to EXTENDED or BASIC, and ESPD-EDM 3.0.0 includes only on single type; 
* Weightings’ validations have been removed because the ESPD-EDM 3.0.0 does not include weights to simplify the model;
* BR related to the CRITERIA removed have been removed accordingly;
* BR related to Code list not used in ESPD-EDM have been removed accordingly; 
* A rule has been added to ensure the proper development of the new Lot Management approach *_(1 Lot/Group of Lots per ESPD Response)_*. ESPD Request includes exclusion and selection criteria for ALL lots while EOs will need to produce an ESPD per Lot tendered. 


=== v2.1.1 (December 2019)

The ESPD EDM version 2.1.1 focuses on correcting minor errors and implementing the backwards-compatible-changes suggested by Member
States and other Stakeholders in the ESPD-EDM in the GitHub link:https://github.com/ESPD/ESPD-EDM/issues[issues workspace].
The list below details exhaustively every change introduced since the publication of the previous release (2.1.0) of the ESPD-EDM:

==== Online documentation

As a part of the improvements introduced by this v2.1.1, the link:https://github.com/ESPD/ESPD-EDM/wiki[ESPD-EDM Wiki] has been refactored in order to offer
users a **Single Information Point**, where it is possible to easly acess to all its resources: documentation, tools, assets, etc.

One of the major novelties in the new v2.1.1 is the nomenclature change to refer the two different *models*: Regulated and Self-Contained, that from now
on will be refered as **Basic** and **Extended**, respectively.

==== TOOP Requirements in ESPD-EDM (UBL2.2) Schema

A mapping for TOOP requirements to UBL2.2 Schema (which is the one used by ESPD-EDM) has been made, and it has been proved that they are
fully mappable. For more information, please refer to the link:https://espd.github.io/ESPD-EDM/v2.1.1/xml_guide.html#II.3.1_UBL-2.2-TOOP-Requirements[dedicated section] of the online documentation.

You can also access to link:https://github.com/ESPD/ESPD-EDM/issues/254[issue #254], where the topic was discussed.

==== Code Lists

* New Criteria OTHER-EO-SME, DEFENCE-SELECTION-OTHER and UTILITIES-SELECTION-OTHER codes have been added to Criteria Taxonomy Code List.
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.1.xlsx[ESPD-CodeLists-V2.1.1.xlsx].

* New code `QUAL_IDENTIFIER` has been added to
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.1.xlsx[ResponseDataType] Code List,
to properly identify the educational qualifications requested in Criterion 47, *SC.ABILITIES.3 (Education)*.

* Two new codes to identify the "new" Basic and Extended models have been added to 
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.1.xlsx[QualificationApplicationType] Code List.

* Missing Canonical Version URI and Location URI have been added to
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.1.xlsx[WeightingType] Code List.

The code lists can be downloaded as an
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.1.xlsx[MS-Excel] or as an
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.1.1.ods[ODS file]. The list
of criteria has been produced based on the CriteriaTaxonomy spread-sheets (both Basic and Extended).

The complete set of code lists has been generated as Genericode 1.0 XML files, which can be
accessed and downloaded from the GitHub repository
link:https://github.com/ESPD/ESPD-EDM/tree/2.1.1/docs/src/main/asciidoc/dist/cl/gc[GC folder].

==== Business Rules

* National grounds are no longer mandatory.

==== ESPD Criteria Taxonomy

* The first question subgroup of Criterion #61: *NOT_RELIED_ON_ENTITITES* of **Basic *model* ** has been rolled-up to the its state on previous v1.0.2 to ensure maximum
compatibility between versions. I.e. "Name of entity", "ID of the entity" and "Activity of the entity" questions have been removed.

The question subgroup of Extended *model* maintaines the structure introduced in v2.0.2.

* New Criterion OTHER-EO-SME has been added to **Extended *model* **, as the UBL code "industry classification" used until now does not allow to give the yes/no answer
included in the Directives.

* The type of "Number of fiscal years" requirement of Criterion #30: *SC-General_Average_Turnover* of **Extended *model* ** has been changed from start date/end date to
QUANTITY_INTEGER.

* New Criteria DEFENCE-SELECTION-OTHER and UTILITIES-SELECTION-OTHER have been created for the specific needs of procedures regulated by Directives 2009/81/EC and 2004/17/EC,
respectively.

* In the selection Criterion #37: SC-REFERENCES ** The cardinality of the first QUESTION, "Recipient name" of QUESTION_SUBGROUP 6afa7569-e4c4-4538-be89-84a82b2a301b has been
changed to 0..1 **.

==== UUIDs

* New UUIDs have been added for the newly created Criteria, groups and sub-groups where needed. For a comprehensive list of the new UUIDs and their
creation reason, please refer to the following link:https://github.com/ESPD/ESPD-EDM/blob/2.1.1/docs/src/main/asciidoc/assets/new_UUIDs_for_eCertis.xlsx[document].

=== v2.1.0 (January 2019)

The ESPD EDM version 2.1.0 focuses on the stabilisation of the previous specification,
notably of the SELF-CONTAINED features. No changes have been introduced in the UBL-2.2 XSD schemas beyond the fact that the
namespace of the XSD Schema is now the final one (as published by the OASIS link:link:http://docs.oasis-open.org/ubl/UBL-2.2.html[UBL-2.2] TC in July 2018).
The list below details exhaustively every change introduced since the publication of the previous release (2.1.0) of the ESPD-EDM:

==== Online documentation

The following sections are new, in the link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html[XML Implementation Guide v2.1.0].

* link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#iv-8-gui-control-elements[IV.8 GUI control elements]: About the sets of data elements (codes
acting as ''processing instructions'') that help software applications control how to show the Graphic User Interfaces
(GUI). The section covers three subjects:

** The use of the link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#ontrue-onfalse-codes-for-group-and-subgroup-control[ONTRUE/ONFALSE] codes for GROUP and SUBGROUP control;
** The use of link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#use-of-caption[CAPTION];
** Ideas for link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#business-data-and-gui-decoupling[decoupling the data from the GUI] in future versions of the ESPD-EDM.
See also the link:[examples] provided to illustrate this idea.

* link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#vi-1-alpha-criterion[VI.1 Alpha criterion]: This section describes how the economic operator (EO) has the possibility,
in the *REGULATED ESPD-Response* document, of specifying that it meets *_all_* the selection criteria (thus avoiding
the specification of each one of the selection criteria specified in the ESPD-Request. This is a special feature
only possible in the *REGULATED ESPD*;

* Some selection criteria have been split in multiples sub-sections, e.g. "Abilities"; this is also explained with more detail below;

* link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#vii-other-aspects-of-participation-and-selection[VII. Other aspects of participation and selection]:
In restricted procedures, competitive procedures with negotiation, competitive dialogue procedures and innovation partnerships, contracting authorities may limit
the number of candidates meeting the selection criteria that they will invite to tender or to conduct a dialogue. To cover this possibility,
the ESPD Regulation introduces a section named "Reduction of the number of qualified candidates" that is not a true selection criterion.
Hence this denomination of "participation criterion".

* link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#ix-putting-pieces-together[IX Putting pieces together]:
The ESPD-EDM specification, notably regarding the SELF-CONTAINED ESPD, defines different complex sets of data that are
scattered in distant locations of the corresponding XML instance. Consequently, implementors of software dealing with
the ESPD XML instances may have a hard time to identify what needs to go in the XML instance and where.
This is the case of, specifically, the data related to topics dealing with special situations like lots, weights and uuids.
To help implementors understand these topics and how to tackle them, the sub-section provides abundant explanations and
examples.

* link:#interoperability-testbed[Interoperability testbed]:
A new section has been added to provide the latest URL to access the interoperability testbed and validate the ESPD document
instances at testing and integration time.

* Other new resources:

** link:https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/doc/evolution/Annotations_Proposal[Examples]
related to the proposal on _how to decouple the GUI from the data structures_ in future versions of the ESPD-EDM;
** link:https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/doc/evolution/StaticPropertyUUIDGeneration_Proposal[Examples]
on how to assign _constant_ UUIDs to the Properties of a Criterion, instead of using dynamically generated UUIDs (a method that
is currently under discussion: see the link:https://github.com/ESPD/ESPD-EDM/issues/226[Issue #226]);
** link:https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/xml[Examples]
provided by the ESPDint solution and other manually adapted for the illustration of Lots, Weights and References.

==== UBL-2.2 Schemas

* The default namespaces for the two UBL-2.2 maindoc used in ESPD are now:
** _urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationRequest-2_
** _urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationResponse-2_
** The rest of all the XSD Schemas namespaces used in UBL-2.2 start now with _urn:oasis:names:specification:ubl:schema:xsd:_, too
** See also how the section
link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#ii-3-ubl-2-2-documents-and-libraries[II.3 UBL-2.2 Documents and libraries]
in the online documentation has been adapted

==== Code Lists

* The criteria taxonomy has been added as a code list to the spread-sheet
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx[ESPD-CodeLists-V2.1.0.xlsx].
This has facilitated the automated generation of the link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/gc/ESPD-CriteriaTaxonomy_V2.1.0.gc[ESPD-CriteriaTaxonomy]
Genericode instance with the UUIDs and Codes of each criterion. The code lists can be downloaded as an
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx[MS-Excel] or as an
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/ods/ESPD-CodeLists-V2.1.0.ods[ODS file]. The list
of criteria has been produced based on the CriteriaTaxonomy spread-sheets (both REGULATED and SELF-CONTAINED).

* New codes have been added to the Code List
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx[ResponseDataType]
to increase the semantics of the basic elements thus facilitating the software application to process the responses of
the economic operator in the SELFCONTAINED ESPD-Response document (the ''semantisation'' also facilitates the validation purposes, e.g.
to ease the validation of whether the attribute schemeID carries a code defined in the
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx[EOIDType] code list).

** `ECONOMIC_OPERATOR_IDENTIFIER`, to detect whether an identifier in the response corresponds to to detect an Economic Operator
** `LOT_IDENTIFIER`, to identify procurement procedure lots in the responses
** `WEIGHT_INDICATOR`, to easily detect that an indicator corresponds to the fact that a criterion is weighted or not
** `CODE_BOOLEAN`, to identify a specific type of GUI control element (e.g. a radio button)

* Two new codes have been added to distinguish the Sole Contractor from the Consortium's Lead Entity. The old SCL one
has been marked as deprecated. See the code list
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx[EORoleType].

* The complete set of code lists has been re-generated as Genericode 1.0 XML files, which can be
accessed and downloaded from the GitHub repository
link:https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/cl/gc[GC folder].

==== Business Rules

The link:https://joinup.ec.europa.eu/solution/interoperability-test-bed[Interoperability Testbed]
has been set up to cope with the link:https://www.itb.ec.europa.eu/espd/upload[validation] of
ESPD-Request and ESPD-Response v2.1.0 documents (click on the arrow of the combo-box 'Validate as').

==== ESPD-REGULATED Criteria Taxonomy

* In previous versions it was decided not to have a criterion named 'Global indication for all selection criteria'
(a.k.a. the "Alpha Criterion") which would avoid the need of specifying long lists of selection criteria. The
description of this criterion, as shown in the transitional EC's ESPD-Service, is
"Concerning the selection criteria the economic operator declares that It satisfies all the required selection
criteria indicated in the relevant notice or in the procurement documents referred to in the notice.". After discussion
the ESPD Working Group decided to retrieve back. Thus a new data structure for the Alpha Criterion has been added to
the REGULATED Criteria Taxonomy spread-sheet.
A new Section has also been added to the online documentation (see section
link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#vi-1-alpha-criterion[VI.1 Alpha Criterion]).

* Exclusion Criteria #7 and #8 (section link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#v-2-contributions[V.2 Contributions])
** The data structures have been redone for better alignment to the ESPD Regulation

* Selection criteria about ''Suitability'' are now split into two types of data structure, ''Enrolments'' and ''Service Contracts''.
See tabs ''Suitability-I'' and ''Suitability-II'' of the
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-REGULATED-V2.1.0.xlsx[ESPD-CriteriaTaxonomy-REGULATED spread-sheet].

* Selection Criterion #32 "Specific yearly turnover" (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY)
** The cardinality of the QUESTION_GROUP c0cd9c1c-e90a-4ff9-bce3-ac0fe31abf16 has been changed from 1 to 1..n

* Selection Criterion #62 (CRITERION.OTHER.EO_DATA.LOTS_TENDERED, See sections
link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#vii-6-1-regulated-economic-operator-party[VIII.6.1 Regulated economic operator party]
and link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#vii-6-2-self-contained-economic-operator-party[VIII.6.2 Self-contained economic operator party].
See also link:https://github.com/ESPD/ESPD-EDM/issues/212[Issue #212])
** The data structure has changed, it now contains only a QUESTION asking for the list of Lots IDs as a free text field (differently to the ESPD-SELFCONTAINED which asks for a collection of LOT_IDENTIFIER data elements).
** The group "Is this information available electronically" has been removed

* Selection Criterion #63 (CRITERION.OTHER.EO_DATA.REDUCTION_OF_CANDIDATES)
** This criterion (named "Contributions certificates") has been removed because it was redundant: the information required therein was also asked in C#58
"EO registered in a PQS" (CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS). More details are provided in the
link:https://github.com/ESPD/ESPD-EDM/issues/227[Issue #227].

* The cardinalities of the block "Is this information available electronically" have been re-adjusted

==== ESPD-SELF-CONTAINED Criteria Taxonomy

* Exclusion Criteria #1 to #6 (section link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#v-1-convictions[V.1 Convictions])
** The UUID of the sub-group of questions referring to the date of conviction, reason, who has been convicted, etc. has
been corrected and is now the same as in the REGULATED version
** The cardinality of the main group of QUESTION(s), with UUID "7c637c0c-7703-4389-ba52-02997a055bd7" (line 11), has changed from 1..n to 1

* Exclusion Criteria #7 and #8 (section link:https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#v-2-contributions[V.2 Contributions])
** The data structures have been redone for better alignment to the ESPD Regulation
** The descriptions of the two criteria have been modified (as there was a mistake in the wording)
** Time lapses that were treated as DESCRIPTIONS are now addressed as PERIODs; e.g. Criteria #7 and #8
** The indentation of the QUESTION inside "Is this information available electronically" has been corrected

*  Selection Criteria #5 to #28 (section link:https://espd.github.io/ESPD-EDM/v2.10/xml_guide.html#vi-2-suitability[VI.2 Suitability]):
**  ''Suitabilities'' are now split into two types of data structure, ''Enrolments'' and ''Service Contracts'' (see also tabs
''Suitability-I'' and ''Suitability-II'' of the
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx[ESPD-CriteriaTaxonomy-SELFCONTAINED spread-sheet]).

* Selection Criterion #24 (CRITERION.EXCLUSION.NATIONAL.OTHER)
** The data structure has been updated, a PropertyDataType NONE was missing in line 6. This is a ''dummy'' element
necessary here because the UBL-2.2 XSD Schema makes mandatory that the first element inside a GROUP or SUBGROUP must
be a `cac:TenderingCriterionProperty`

* Selection Criteria #31 and #32 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_AVERAGE and
CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY, see section
link:https://espd.github.io/ESPD-EDM/v2.10/xml_guide.html#vi-3-turnovers[VI.3 Turnovers])
** The REQUIREMENT "Number of fiscal years" has been corrected (from AMOUNT to QUANTITY_INTEGER).

* Selection Criteria #33 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SET_UP)
** The property data type of the field 'Please specify' (in line 12) has changed from DESCRIPTION to DATE

* Selection Criterion #35 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE, see section
link:https://espd.github.io/ESPD-EDM/v2.10/xml_guide.html#vi-6-2-self-contained-risk-indemnity-insurance[VI.6.2 Self-contained risk indemnity insurance])
** The property data type for the identification of Lot ID in the CA requirement has changed to LOT_IDENTIFIER
** Cardinality in Structure "Is this information available electronically" QUESTION has been changed to 1..n
** Wrongly indented QUESTION has been corrected (in the structure "Is this information available electronically")

* Selection Criterion #36 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENT(s), see section
link:https://espd.github.io/ESPD-EDM/v2.10/xml_guide.html#vi-7-2-self-contained-other-economic-or-financial-requirements[VI.7.2 Self-contained other economic or financial requirements])
** The property data type for the identification of Lot ID in the CA requirement has changed to LOT_IDENTIFIER
** UUIDs added
** Cardinality corrected

* Selection Criterion #36 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENT(s))
** Wrongly indented QUESTION has been corrected (in the structure "Is this information available electronically")

* Selection Criterion #38 (CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE, see
the criterion Data Structure in section ''VI.8.2 Self-contained references'' and in the SELF-CONTAINED Criteria Taxonomy
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx[spread-sheet]
tab ''SC-References'')
** REQUIREMENT(s) regarding the identifiers of Lots are now semantised as LOT_IDENTIFIER
** Cardinality of the QUESTION in the block "Is the information available electronically" has been corrected (from 1 to 1..n)

* Selection Criterion #39 (CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SERVICES_DELIVERY_PERFORMANCE, see the
link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx[Criteria Taxonomy]
for the SELF-CONTAINED ESPD and section ''VI.8.2 Self-contained references'')
** Description has been corrected. It now reads "For public service contracts only: During the reference period, the economic operator has provided the following main services of the type specified. Contracting authorities may require up to three years and allow experience dating from more than three years.".

* Selection Criteria #40 to #51 about ''Abilities'' have been split into 5 different data structures
(See these tabs in the
 link:https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx[ESPD-CriteriaTaxonomy-SELFCONTAINED spread-sheet])

** SC-Abilities_1 (Persons), Criteria #40 and #41 (technicians)
** SC-Abilities_2 (Facilities), Criteria #42 to #46 (about facilities, studies, supply chain, etc.)
** SC-Abilities_3 (Education), Criterion #47 (about educational and professional qualifications). Concerning this
Criterion, an Information Box has also been added to explain what is ESCO, the need of using URLs to identify the
Qualifications and where to find additional information about ESCO (see also information box and XML example in
section ''VI.9.6 Self-contained Abilities (III) - Education'')
* SC-Abilities_4 (Checks), Criterion #48 (about allowance of checks), and
** SC-Abilities_5 (Staff), about the contractor's personnel

* Selection Criteria #41 (CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.TECHNICIANS_FOR_CARRYING_WORKS)
** The word _waited_ was replaced with _weighted_ in different places of the criterion.

* Selection Criteria #52 and #53 (Samples and certificates, section 'VI.11 Samples and certificates')
** An indentation was corrected in Criteria 52 and 53. The QUESTION tag was misplaced and hidden.

* Selection Criterion #57 (CRITERION.OTHER.EO_DATA.SHELTERED_WORKSHOP)
** Wrongly indented tag {QUESTION} has been corrected.

* Selection Criterion #58 (CRITERION.OTHER.EO_DATA.REGISTERED_IN_OFFICIAL_LIST)
** The data structure has changed, the CAPTION "If the relevant documentation is available electronically, please provide it" has been removed. The use of the block "Is this information available electronically" (UUID) must be used for that specific purpose.

* Selection Criterion #59 (CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS)
** The data structure of this criterion has been modified to align it to the one in the REGULATED ESPD
** A CODE property data type has replaced the type IDENTIFIER (which was wrongly assigned to the field 'Please indicate
the role of the economic operator in the group (leader, responsible for specific tasks...)' in line 8).

* Selection Criteria #60 (Relied on entities, CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES)
** In Criterion 60, the DataPropertyTypes ECONOMIC_OPERATOR_IDENTIFIER has replaced IDENTIFIER in line 8
** CODE has replaced DESCRIPTION in line 9
** Wrongly indented tag {QUESTION} has also been corrected.

* Selection Criterion #61 (CRITERION.OTHER.EO_DATA.SUBCONTRACTS_WITH_THIRD_PARTIES. The code list to be used is the
maintained in SIMAP for CodeLists (https://simap.ted.europa.eu/cpv)
** ID of the subcontractor has been semantised from IDENTIFIER to ECONOMIC_OPERATOR_ID
** The field 'Activity of the entity (for this specific procedure) can now be expressed as a set of one or more CPV codes

* Selection Criterion #62 (CRITERION.OTHER.EO_DATA.LOTS_TENDERED, See sections ''VIII.6.1 Regulated economic operator party'' and ''VIII.6.2 Self-contained economic operator party'')
** The group "Is this information available electronically" has been removed
** Wrongly indented tag {QUESTION} has been corrected.

* Selection Criterion #63 (CRITERION.OTHER.EO_DATA.REDUCTION_OF_CANDIDATES)
** This criterion (named "Contributions certificates") has been removed because it was redundant: the information required therein was also asked in C#58
"EO registered in a PQS" (CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS). More details are provided in the
link:https://github.com/ESPD/ESPD-EDM/issues/227[Issue #227].

* The cardinalities of the block "Is this information available electronically" have been re-adjusted

==== UUIDs

* Criteria UUIDs are not backwards-consistent (with versions 1.0.2, 2.0.*). New UUIDs have been added for the new
ESPD-SELF-CONTAINED groups and sub-groups where needed. All corrected and new UUIDs are red-coloured in the
CriteriaTaxonomy spread-sheets.

=== v2.0.2 (May 2018)

The ESPD EDM version 2.0.2 is now released and contains only bugs fixed on the basis of the received comments on GitHub.
The release contains a definition of all relevant
business rules and corresponding schematron files to validate Regulate and Self-Contained ESPD Request and Response XML instances
(including the validation of the criteria taxonomy). The corresponding TestBed for version 2.1.1 has been set up.
The specifications for version 2.0.2 contain an updated distribution of the ESPD Exchange Data Model and include a corresponding implementation guideline
which clarifies the ESPD validation architecture in Annex I. Also, the BIS 41 – ESPD version 2.0.2 was updated accordingly.

This release encompasses these other minor updates:

* **Code lists**

** A new code list has been added: "WeightingType". Reason: some selection criteria need to be weighted. In version 2.0.0 the element "cbc:WeightingTypeCode" was added to the root of the "UBL-QualificationApplicationResponse-2.2-Pre-award.xd" document.
** Two code lists have been removed as they are not used anymore in versions 2.0.x: `PeriodMeasureTypeCodes` and `TechnicalCapabilityTypeCode`.

* **Criteria data structures**

** All criteria have now one block "Is this information available electronically" with cardinality 0..n. See data structures spread-sheets for both
the link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/ESPD-CriteriaTaxonomy-REGULATED-V2.0.2.ods[REGULATED] and the
link:https://github.com/ESPD/ESPD-EDM/blob/2.0.2/docs/src/main/asciidoc/dist/cl/ods/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.ods[SELF-CONTAINED] models.

** In the *SELF-CONTAINED ESPD* CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE Subgroup "83e3dcc4-c9b3-47e5-9fb8-ffd8386679f1" changed its cardinality from 1 to 1..n.

** In "Financial Ratios" for the SELF-CONTAINED ESPD, the REQUIREMENT "Ratio Type" needs to be a CODE (not a DESCRIPTION, as in previous versions). This code is needed by the Contracting Authority
to specify the BACH's code (See section "VI.4.2 Self-contained financial ratios" of the online documentation for details on this).

* **UUIDS**

** In the previous versions the UUIDs for the block "Is this information available electronically" where not 100% consistent. For some criteria they used the same UUIDs as in version 1.0.2 and for other a completely different set of UUIDS.
This has been corrected and now all criteria have one block "Is this information available electronically", and all of them use the same UUIDs (the ones used also in version 1.0.2).

=== v2.0.1 (1st February 2018)

The changes specified herein have been applied in both (1) the link:++https://github.com/ESPD/ESPD-EDM++[ESPD-EDM specification], version 2.1.1 published in this Github repository; and (2) the link:++http://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.1.1++[ESPDInt BIS document].

See also details in: link:++https://github.com/ESPD/ESPD-EDM/tree/2.1.1/docs/src/main/asciidoc/dist/rn/Release Notes-2.1.1.ods++[Release Notes Details] and in this Github "Issues" section.

* *Code Lists*:

** The "ActivityType", "AmountTypeCode" and "ContractType" Code Lists have been removed, as they're not used. The Code List "ContractType" is covered (i.e. replaced) by the CodeList "ProcedureType". The ESPDInt BIS document has been modified accordingly: Section about Code Lists has been updated.

* *Use of the UBL-2.2 Schemas elements*:

** The UBL-2.2 element `ProfileExecutionID` is used now to compulsorily specify the version and *model* of the ESPD-EDM. See the possible values in the Code List "ProfileExecutionID" (e.g. "ESPD-EDMv2.0.0-REGULATED", "ESPD-EDMv2.0.0-SELFCONTAINED", "ESPD-EDMv2.1.1-REGULATED", "ESPD-EDMv2.1.1-SELFCONTAINED"...see also the Guideline and XML examples. Remember also that cardinalities are to be controlled via business rule). The ESPDInt BIS document has been modified accordingly: Inclusion of the ESPD version identifier (tir070-299;tir092-299). The following Business Rules have been added: TRDM092-55, TRDM072-36 for tir92-299 and tir070-299 to control the Evidence version.

** The v2.0.0 documentation specified in section "VIII.5 Reference to publications and to the ESPD Request" that the elements `cac:QualificationApplicationRequest/cac:AdditionalDocumentReference/cbc:ID` and `cac:QualificationApplicationRequest/cac:AdditionalDocumentReference/cbc:UUID` had to be used to refer to other documents. This was an editorial error and has been corrected: the elements to be referred are: `cac:QualificationApplicationRequest/cbc:ID` and `cac:QualificationApplicationRequest/cbc:UUID`.

** Element `cac:ProcurementProject` (cardinality 0..1): Use this component to identify and describe the procurement administrative procedure. The REGULATED version should not contain a `cac:ProcurementProject` in order to ensure the back-wards compatibility with the version 1.0.2. Use this component in case the ESPD is SELF-CONTAINED and the procedure is divided into lots. In this case use the `ProcurementProjectLot` component to provide details specific to the lot and reserve the `ProcurementProject` component to describe the global characteristics of the procedure.

* *ESPD-EDM Cardinalities*:

** The ESPD-EDM cardinality for the element `cac:TenderingCriterionResponse/cac:ResponseValue` has been modified to 0..n (see the online ESPD-EDM documentation).

** The cardinality of the element `cac:Evidence/cbc:ID` is now mandatory (to be controlled via business rule, as the UBL-XSD is 0..1). The ESPDInt BIS document has been modified accordingly.

** About elements of `cac:ProcurementProject`:

*** The cardinality of `cbc:ProcurementTypeCode` is now '0..1' in both the REGULATED and the SELFCONTAINED ESPD Requests (Thus ensuring compatibility between version 2.1.1 REGULATED and v1.0.2). The ESPDInt BIS document has been modified accordingly: Cardinality for the class Procurement Project and the subordinated elements tir070-503, tir070-504, tir92-505, tir92-506 from 1..1 to 0..1 has been changed.

*** The cardinality of `cbc:Name` is now 0.1 in both the REGULATED and the SELFCONTAINED ESPD Requests. If used the text must match the one used in the Contract Notice.

*** The cardinality of `cbc:Description` is now 0.n in both the REGULATED and the SELFCONTAINED ESPD Requests (thus ensuring compatibility with UBL-2.2 multi-line descriptions). If used the text must match the one used in the Contract Notice.

*** ESPDInt BIS document: Adding cardinalitites for "Evidence issuer party" and "Criterion fulfillment URI".

* *UUIDS reviewed*: UUIDs, names and descriptions in files ESPD-REGULATED-CriteriaTaxonomy-V02.00.01 and ESPD-SELFCONTAINED-CriteriaTaxonomy-V02.00.01.xlsx do match now the ones in ESPD-Data_Structures-REGULATED-V02.00.01 and ESPD-Data_Structures-SELFCONTAINED-V02.00.01 spreadsheet books. Some UUIDS for subgroups of requirements have also been corrected (e.g. SC-General_Turnover --> 5ca58d66-3ef1-4145-957c-45d5b18a837f,  SC-Specific_Turnover --> 19a68e37-d307-4a28-9061-c22cd767be58, SC-General_Average_Turnover --> 53882893-f4a8-40ae-99dc-cad7b0748790, SC-Specific_Average_Turnover --> 6cff132b-8d15-4f79-ae37-2f9295432381).

* *Data Structures*:

** Information available electronically: The group "Is this information available electronically" is now present i all the criteria data structures (see "Data Structures" in the "dist/cl" files).

** Some codes "ON*" were erroneous and have been transformed into "ONTRUE", e.g.Criterion 22 in the REGULATED Data Structures spreadsheets book AND Criterion 22 in the SELF-CONTAINED Data Structures spreadsheets book.

** Missing data types: Some data types were missing and have been added; e.g. compare criteria 9 to 11, and criteria 62 and 63 between versions 2.0.0 and version 2.1.1.

The ESPDInt BIS document has been aligned accordingly.

* *Editorial corrections*:

** ESPD-EDM specification:

*** The definitions in the Data Structure spread-sheets containing syntax and grammar errors have been corrected (based on the texts on the Regulation Annex II and ESPD Service GUI). Additional comments have also been added in the online documentation about the use of the UBL-2.2 0..n multi-line descriptions, as requested by some users.

*** Requirement about LotsThe documentation (in version 2.1.1) has been modified and reads now "One Lot must be always instantiated in the REGULATED ESPD XML document, and its identifier value should be '0'. The REGULATED version of the ESPD cannot be used for procurement procedures divided into Lots. For procedures divided into Lots use the SELF-CONTAINED version.

*** Additional explanatory texts have been added at the beginning of sections "VI.2.6 Self-contained specific yearly turnover" and "VI.2.8 Self-contained specific average turnover" to clarify the use of CPVs.

*** Group "Is this information available electronically": Beware that in version 2.0.0 this sentence was phrased differently as "Is this information available at no cost to the authorities from an EU Member State database?".

*** Enhanced description of the codes ON*, ONTRUE,ONFALSE, and other Data Structure elements: A sub-section "IV.4 Mock-ups, data structures, XML examples and tools" has been added to the online documentation explaining the meaning and use of each column of the Data Structures.

*** The figures representing the criteria taxonomies (both exclusion grounds and selection criteria) are now aligned with the criteria defined in the CriteriaTaxonomy and Data Structure spread-sheets (compare images in sections "V. Exclusion criteria", "VI. Selection criteria" and these files located in the "dist/cl" folder).

** ESPDInt BIS document:

*** "Customization Identifier" for the Request and the Response to the section "Identifiers" added.
*** Name of the ListIDs named in the Business Rules TRDM092-33 and TRDM070-BR-22 has been modified.
*** Implementation Guideline for tir070-061 and tir92-071 modified.
*** `tir70-502` added to reflect the country name.
*** Illustration of the differences between the regulated and the self-contained ESPD in data models and implementation guidelines.


* *ESPD-EDM specification artefacts*:

** The content of the "dist/xlst" folder has been enriched and reorganised as follows:

*** The stylesheets used to transform the Data Structure *.ods files into ESPD-EDM XML instances are now under the folder 'dist\xslt\ODS Data Structures to ESPD XML'. New files have been added to this folder to help with the automation of the generation of the bunch of all the data structures in a go: e.g. ESPD-Transformation.jar, ESPD-Transformer.bat. The use of these files is explained in section "IV.4 Mock-ups, data structures, XML examples and tools", subsection "Data structures spread-sheets as a tool to generate XML instances" of the documentation.

*** A new folder named "XLSX CodeLists to Genericode" contains a style-sheet that can be used to generate OASIS Genericode 1.0 *.gc files (see "dist/cl/gc" folder) out of the spread-sheets book containing the Code Lists (file "dist/cl/xlsx/ESPD-CodeLists-V02.00.01.xlsx"). Please read the README.txt file inside this folder with the usage instructions.


* *Business Rules*:

** Modifications applied to the ESPDInt BIS document (aligned to the modifications on the ESPD-EDM specification):

*** Changing path mentioned in the following Business Rules: TRDM092-13, TRDM092-14 and in the following implementation guidelines tir92-543, tir92-309.
*** Adding the following Business Rules: TRDM092-56, TRDM072-37 for tir070-601, tir092-601 to control the criterion requirement structure.
*** Adding the following Business Rules: TRDM092-57 for tir92-525 to control the confidentiality of responses.
*** Removed the element "Postbox" from all address classes.
*** Extended requirement description of tbr070-002 and tbr92-019
*** Adding the following elements tir070-601, tir092-601
*** Adding the Business Rule TRDM092-58 for tir092-526 to control the Criterion Property Groups

=== v2.0.0 (25th July 2017)

. Adoption of UBL-2.2 XSD Schemata;
. Introduction of REGULATED and SELFCONTAINED ESPD

=== v1.0.2 (28th of July 2016)

* https://github.com/ESPD/ESPD-EDM/issues/2[Change cardinality of requirements inside requirement groups].
