
=== VI.7 Other economic or financial requirements

==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Basic and Extended

. In the *Basic* ESPD it is the economic operator who declares other economic and financial information.

. In the *Extended* ESPD the contracting authority can specify the description of the economic or financial requirement; the minimum amount required and the currency; the period to which the amount relates to; a minimum rating and the rating schema. 

. In the *Extended* the contracting authority can also specify the Lots to which the economic or financial requirement applies. This is not possible in the *Basic* ESPD.

. The *Extended* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis.

. For both models, *Basic* and *Extended*, the only criterion defined is classified with the code:

	** CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENT(s)
	
