
=== VI.8 References on similar works, deliveries or services


==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Basic and Extended

. For both models, *Basic* and *Extended* the contracting authority can require references for the type of project (or nature of the contract: works, supplies and services). Software applications should take care of not including those types of contract that were not selected by the contracting authority.

. In the *Basic* ESPD the economic operator supplies its references for one of those types of contract.

. In the *Basic* ESPD the economic operator provides a description for the reference, the amount of the contract, the period of execution and who where the recipients of its works, supplies or services. 'Amount' here must be interpreted as the amount specific to this reference. See difference between total and specific amounts below.

. In the *Extended* ESPD the contracting authority can specify the minimum number of references required for the evaluation; an an unlimited number of free-text “requirements”, so the CA can provide requirements very specific to the procurement procedure. 

. In the *Extended* ESPD, and per each reference, the economic operator (EO) can specify more information than for the *Basic* ESPD; e.g. the Lots to which the reference applies; the 'total amount'  and the 'specific amount', the 'activity' of the economic operator in this reference, the period of time the execution or performance took, whether this reference must be treated as confidential or not, and the 'receipients' of this reference.

. The *Extended* is able to keep in the XML documents the national sub-criteria defined by the MS in e-Certis.

. For both models, *Basic* and *Extended*, there are three criteria with the same data structure (works, supplies and services references):

	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.WORKS_PERFORMANCE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SERVICES_DELIVERY_PERFORMANCE

.Difference between 'total amount' and 'specific amount' in a reference
[NOTE]
====
The total amount refers to the amount of the contract, the specific refers to the amount of the contract a concrete reference is linked to. Two examples could be:

. A contract for the acquisition of printers (Lot1) and the maintenance of the printers (Lot2). Your reference is about the maintenance only. Total amount: 1,000,000 € (Lot1 + Lot 2). Specific amount: 700,000.00 (Lot2, maintenance).

. Building of a bridge. Total amount: 20,000,000 €. The reference is only about the asphalt provided for the bridge: specific amount 1,351,145.89 €.

====