
=== VI.12 Quality assurance


==== Related information requirements

See formal requirements related to selection criteria in the http://wiki.ds.unipi.gr/pages/viewpage.action?pageId=44367916[BIS 41 - European Single Procurement Document (Version 2.0.0)].


==== Differences between Regulated and Self-contained

. In the *REGULATED* version the contracting authority (CA) cannot specify REQUIREMENT(s).

. For both versions, *REGULATED* and *SELF-CONTAINED*, the economic operator is expected to answer *Yes* or *No*. 

** If the EO answers *Yes* the EO will be asked whether there are evidences available online.
** In the case the EO answers *NO* it will have to provide additional explanations.

. In the *SELF-CONTAINED* version the contracting authority can provide as many REQUIREMENT(s) as needed in a textual field, normally the type of standard it expects the EO conforms to, e.g. 'ISO 9001', 'EMAS', etc. (but it could issue any other type of REQUIREMENT as a text).

. The *SELF-CONTAINED* is able to keep in the XML documents national sub-criteria defined by the MS in e-Certis.

. For both versions, *REGULATED* and *SELF-CONTAINED*, there are three criteria that share the same data structure, classified as:

	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.QUALITY_ASSURANCE.QA_INSTITUTES_CERTIFICATE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.QUALITY_ASSURANCE.QA_INDEPENDENT_CERTIFICATE
	** CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.CERTIFICATES.ENVIRONMENTAL_MANAGEMENT.ENV_INDEPENDENT_CERTIFICATE
